{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 14:57:34 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-0.8975979,-0.7724138,3.590392,24.97471);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,7);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(2,6);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,16);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,13);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(5,7);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(6,6);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(9,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(10,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(12,2);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(14,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(15,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(16,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(17,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(19,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(22,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,2.645751);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(2,2.44949);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,4);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,3.605551);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(5,2.645751);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(6,2.44949);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(9,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(10,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(12,1.414214);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(14,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(15,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(16,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(17,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(19,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(22,1);
   sigWta_MinDeltaPhiMetAllJets->SetMinimum(0);
   sigWta_MinDeltaPhiMetAllJets->SetMaximum(22.4);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(76);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerSize(0.8);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(999);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitle("Events");
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.095);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(0.85);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_3 = new TH1F("h1_stack_3","h1",22,0,3.141593);
   h1_stack_3->SetMinimum(0);
   h1_stack_3->SetMaximum(15.72441);
   h1_stack_3->SetDirectory(0);
   h1_stack_3->SetStats(0);
   h1_stack_3->SetLineStyle(0);
   h1_stack_3->SetMarkerStyle(20);
   h1_stack_3->GetXaxis()->SetNdivisions(505);
   h1_stack_3->GetXaxis()->SetLabelFont(42);
   h1_stack_3->GetXaxis()->SetLabelOffset(999);
   h1_stack_3->GetXaxis()->SetLabelSize(0);
   h1_stack_3->GetXaxis()->SetTitleSize(0.06);
   h1_stack_3->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_3->GetXaxis()->SetTitleFont(42);
   h1_stack_3->GetYaxis()->SetNdivisions(505);
   h1_stack_3->GetYaxis()->SetLabelFont(42);
   h1_stack_3->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetYaxis()->SetLabelSize(0.06);
   h1_stack_3->GetYaxis()->SetTitleSize(0.095);
   h1_stack_3->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_3->GetZaxis()->SetNdivisions(505);
   h1_stack_3->GetZaxis()->SetLabelFont(42);
   h1_stack_3->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetZaxis()->SetLabelSize(0.03);
   h1_stack_3->GetZaxis()->SetTitleSize(0.06);
   h1_stack_3->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_3);
   
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,2.697554);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(2,0.5558296);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,3.847602);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,0.372188);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(5,1.53313);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(6,0.6435988);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,0.1841265);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(9,1.198513);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(18,0.286095);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(19,0.4277845);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,1.359105);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(2,0.5558296);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,1.532493);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,0.372188);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(5,0.9007658);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(6,0.6435988);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,0.1841265);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(9,0.9713582);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(18,0.286095);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(19,0.4277845);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(22);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#9999cc");
   sigWta_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#9999cc");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,0.07265084);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,0.08726405);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,0.1077165);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,0.02847289);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,0.07547176);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(12,0.07025725);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(16,0.03289988);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(19,0.02892624);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,0.07265084);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,0.08726405);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,0.1077165);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,0.02847289);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,0.07547176);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(12,0.07025725);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(16,0.02940391);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(19,0.02892624);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(9);

   ci = TColor::GetColor("#669966");
   sigWta_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,0.3613125);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(2,1.089995);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,0.5245731);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(5,0.01429921);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(6,0.01288879);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,0.8617605);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,0.01392364);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,0.01740732);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(14,0.2901098);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(18,0.00825379);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(20,0.007931719);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,0.3613125);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(2,0.7983992);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,0.511054);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(5,0.01429921);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(6,0.01288879);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,0.8364607);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,0.01392364);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,0.0128813);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(14,0.2770483);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(18,0.00825379);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(20,0.007931719);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(78);

   ci = TColor::GetColor("#cc6600");
   sigWta_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#cc6600");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,0.0118206);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,0.02206686);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(9,0.0097103);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,0.01276305);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,0.01367805);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(14,0.01514764);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(15,1.194431);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(17,1.196697);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(20,0.01328668);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,0.0118206);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,0.01617197);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(9,0.0097103);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,0.01276305);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,0.01367805);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(14,0.01514764);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(15,1.194431);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(17,1.196697);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(20,0.01328668);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(27);

   ci = TColor::GetColor("#ffcc66");
   sigWta_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc66");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,0.7259528);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(2,8.834776);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,11.01869);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,6.481107);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(5,7.098689);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(6,6.877882);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(7,3.108296);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,0.7397033);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(9,1.075824);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(10,1.656246);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,0.08466728);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(12,0.4879646);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,0.0679771);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(14,0.09007785);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(15,0.5635223);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(16,0.675489);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(17,1.104798);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(18,0.282307);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(19,0.02141897);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(20,1.037312);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(21,0.04534576);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(22,0.0219508);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,0.4526504);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(2,2.111793);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,2.229331);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,1.788121);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(5,2.198481);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(6,1.888284);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(7,1.364818);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,0.5496323);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(9,0.6949642);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(10,0.7711332);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,0.02971087);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(12,0.3990492);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,0.02836531);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(14,0.03507688);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(15,0.5350442);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(16,0.6086222);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(17,1.079931);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(18,0.2526196);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(19,0.01518321);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(20,0.7245891);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(21,0.02285356);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(22,0.01338618);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(1909);

   ci = TColor::GetColor("#993300");
   sigWta_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#993300");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_MinDeltaPhiMetAllJets,"");
   h1->Draw("histsame");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(1,7);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(2,6);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,16);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(4,13);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(5,7);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(6,6);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(8,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(9,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(10,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(11,3);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(12,2);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(14,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(15,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(16,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(17,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(19,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(22,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(1,2.645751);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(2,2.44949);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,4);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(4,3.605551);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(5,2.645751);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(6,2.44949);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(8,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(9,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(10,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(11,1.732051);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(12,1.414214);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(14,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(15,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(16,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(17,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(19,1);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(22,1);
   sigWta_MinDeltaPhiMetAllJets->SetMinimum(0);
   sigWta_MinDeltaPhiMetAllJets->SetMaximum(22.4);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(76);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerSize(0.8);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(999);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitle("Events");
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.095);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(0.85);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->Draw("P0E1same");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(3,2.273738);
   sigWta_MinDeltaPhiMetAllJets->SetBinContent(13,1.678473);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(3,2.273738);
   sigWta_MinDeltaPhiMetAllJets->SetBinError(13,1.678473);
   sigWta_MinDeltaPhiMetAllJets->SetEntries(2);

   ci = TColor::GetColor("#ff0000");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetLineWidth(3);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->Draw("HISTsame");
   
   TH1D *sigWta_MinDeltaPhiMetAllJets = new TH1D("sigWta_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,0,3.141593);

   ci = TColor::GetColor("#0000ff");
   sigWta_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWta_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets->SetLineWidth(3);
   sigWta_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWta_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets->Draw("HISTsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","Top","F");

   ci = TColor::GetColor("#9999cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#9999cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","W#rightarrow e#nu","F");

   ci = TColor::GetColor("#cc6600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc6600");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","W#rightarrow#mu#nu","F");

   ci = TColor::GetColor("#ffcc66");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc66");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","W#rightarrow#tau#nu","F");

   ci = TColor::GetColor("#993300");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#993300");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","Signal (x1)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_MinDeltaPhiMetAllJets","gg#rightarrow H (x1)","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigWta_MinDeltaPhiMetAllJets__3 = new TH1D("sigWta_MinDeltaPhiMetAllJets__3","MinDeltaPhiMetAllJets",22,0,3.141593);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(1,7);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(2,6);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(3,16);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(4,13);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(5,7);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(6,6);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(8,3);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(9,3);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(10,3);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(11,3);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(12,2);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(13,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(14,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(15,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(16,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(17,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(19,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinContent(22,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(1,2.645751);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(2,2.44949);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(3,4);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(4,3.605551);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(5,2.645751);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(6,2.44949);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(8,1.732051);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(9,1.732051);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(10,1.732051);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(11,1.732051);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(12,1.414214);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(13,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(14,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(15,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(16,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(17,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(19,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetBinError(22,1);
   sigWta_MinDeltaPhiMetAllJets__3->SetMinimum(0);
   sigWta_MinDeltaPhiMetAllJets__3->SetMaximum(22.4);
   sigWta_MinDeltaPhiMetAllJets__3->SetEntries(76);
   sigWta_MinDeltaPhiMetAllJets__3->SetDirectory(0);
   sigWta_MinDeltaPhiMetAllJets__3->SetLineStyle(0);
   sigWta_MinDeltaPhiMetAllJets__3->SetMarkerStyle(20);
   sigWta_MinDeltaPhiMetAllJets__3->SetMarkerSize(0.8);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelOffset(999);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelSize(0);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleOffset(0.9);
   sigWta_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitle("Events");
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelSize(0.06);
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitleSize(0.095);
   sigWta_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitleOffset(0.85);
   sigWta_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelFont(42);
   sigWta_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelOffset(0.007);
   sigWta_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelSize(0.05);
   sigWta_MinDeltaPhiMetAllJets__3->GetZaxis()->SetTitleSize(0.06);
   sigWta_MinDeltaPhiMetAllJets__3->GetZaxis()->SetTitleFont(42);
   sigWta_MinDeltaPhiMetAllJets__3->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(-0.8975979,-1.914893,3.590392,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",22,0,3.141593);
   h1_num->SetBinContent(1,1.809117);
   h1_num->SetBinContent(2,0.5724862);
   h1_num->SetBinContent(3,1.068403);
   h1_num->SetBinContent(4,1.736671);
   h1_num->SetBinContent(5,0.8096119);
   h1_num->SetBinContent(6,0.7963507);
   h1_num->SetBinContent(8,1.653746);
   h1_num->SetBinContent(9,1.313458);
   h1_num->SetBinContent(10,1.811325);
   h1_num->SetBinContent(11,16.05775);
   h1_num->SetBinContent(12,3.582805);
   h1_num->SetBinContent(13,10.09464);
   h1_num->SetBinContent(14,2.529498);
   h1_num->SetBinContent(15,0.5688433);
   h1_num->SetBinContent(16,1.411654);
   h1_num->SetBinContent(17,0.4345002);
   h1_num->SetBinContent(19,2.091483);
   h1_num->SetBinContent(22,45.55643);
   h1_num->SetBinError(1,0.9725648);
   h1_num->SetBinError(2,0.2659954);
   h1_num->SetBinError(3,0.3295941);
   h1_num->SetBinError(4,0.6528699);
   h1_num->SetBinError(5,0.3783312);
   h1_num->SetBinError(6,0.3875031);
   h1_num->SetBinError(8,1.33154);
   h1_num->SetBinError(9,1.023144);
   h1_num->SetBinError(10,1.343447);
   h1_num->SetBinError(11,11.71265);
   h1_num->SetBinError(12,3.630607);
   h1_num->SetBinError(13,10.67344);
   h1_num->SetBinError(14,3.098457);
   h1_num->SetBinError(15,0.7091806);
   h1_num->SetBinError(16,1.862038);
   h1_num->SetBinError(17,0.5304713);
   h1_num->SetBinError(19,2.81004);
   h1_num->SetBinError(22,53.35918);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(2.808215);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(0,1,3.141593,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
