{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 14:57:34 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(925.7143,-1.496552,2297.143,48.38851);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,31);
   sigWta_Dijet_Mjj->SetBinContent(2,17);
   sigWta_Dijet_Mjj->SetBinContent(3,6);
   sigWta_Dijet_Mjj->SetBinContent(4,9);
   sigWta_Dijet_Mjj->SetBinContent(5,5);
   sigWta_Dijet_Mjj->SetBinContent(6,2);
   sigWta_Dijet_Mjj->SetBinContent(7,6);
   sigWta_Dijet_Mjj->SetBinError(1,5.567764);
   sigWta_Dijet_Mjj->SetBinError(2,4.123106);
   sigWta_Dijet_Mjj->SetBinError(3,2.44949);
   sigWta_Dijet_Mjj->SetBinError(4,3);
   sigWta_Dijet_Mjj->SetBinError(5,2.236068);
   sigWta_Dijet_Mjj->SetBinError(6,1.414214);
   sigWta_Dijet_Mjj->SetBinError(7,2.44949);
   sigWta_Dijet_Mjj->SetMinimum(0);
   sigWta_Dijet_Mjj->SetMaximum(43.4);
   sigWta_Dijet_Mjj->SetEntries(76);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->SetMarkerSize(0.8);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(999);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitle("Events");
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.095);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(0.85);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_1 = new TH1F("h1_stack_1","h1",6,1200,2160);
   h1_stack_1->SetMinimum(0);
   h1_stack_1->SetMaximum(24.24249);
   h1_stack_1->SetDirectory(0);
   h1_stack_1->SetStats(0);
   h1_stack_1->SetLineStyle(0);
   h1_stack_1->SetMarkerStyle(20);
   h1_stack_1->GetXaxis()->SetNdivisions(505);
   h1_stack_1->GetXaxis()->SetLabelFont(42);
   h1_stack_1->GetXaxis()->SetLabelOffset(999);
   h1_stack_1->GetXaxis()->SetLabelSize(0);
   h1_stack_1->GetXaxis()->SetTitleSize(0.06);
   h1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_1->GetXaxis()->SetTitleFont(42);
   h1_stack_1->GetYaxis()->SetNdivisions(505);
   h1_stack_1->GetYaxis()->SetLabelFont(42);
   h1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_1->GetYaxis()->SetLabelSize(0.06);
   h1_stack_1->GetYaxis()->SetTitleSize(0.095);
   h1_stack_1->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_1->GetZaxis()->SetNdivisions(505);
   h1_stack_1->GetZaxis()->SetLabelFont(42);
   h1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_1->GetZaxis()->SetLabelSize(0.03);
   h1_stack_1->GetZaxis()->SetTitleSize(0.06);
   h1_stack_1->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_1);
   
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,2.851325);
   sigWta_Dijet_Mjj->SetBinContent(2,3.63113);
   sigWta_Dijet_Mjj->SetBinContent(3,2.78996);
   sigWta_Dijet_Mjj->SetBinContent(4,1.497034);
   sigWta_Dijet_Mjj->SetBinContent(5,0.3770623);
   sigWta_Dijet_Mjj->SetBinContent(6,0.5999097);
   sigWta_Dijet_Mjj->SetBinError(1,1.350732);
   sigWta_Dijet_Mjj->SetBinError(2,1.486975);
   sigWta_Dijet_Mjj->SetBinError(3,1.346892);
   sigWta_Dijet_Mjj->SetBinError(4,0.871378);
   sigWta_Dijet_Mjj->SetBinError(5,0.3770623);
   sigWta_Dijet_Mjj->SetBinError(6,0.5999097);
   sigWta_Dijet_Mjj->SetEntries(22);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#9999cc");
   sigWta_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#9999cc");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_Dijet_Mjj,"");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,0.2397998);
   sigWta_Dijet_Mjj->SetBinContent(2,0.1883878);
   sigWta_Dijet_Mjj->SetBinContent(6,0.07547176);
   sigWta_Dijet_Mjj->SetBinError(1,0.1350564);
   sigWta_Dijet_Mjj->SetBinError(2,0.1170635);
   sigWta_Dijet_Mjj->SetBinError(6,0.07547176);
   sigWta_Dijet_Mjj->SetEntries(9);

   ci = TColor::GetColor("#669966");
   sigWta_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_Dijet_Mjj,"");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,1.484792);
   sigWta_Dijet_Mjj->SetBinContent(2,0.9048121);
   sigWta_Dijet_Mjj->SetBinContent(3,0.5222036);
   sigWta_Dijet_Mjj->SetBinContent(4,0.2767248);
   sigWta_Dijet_Mjj->SetBinContent(6,0.01392364);
   sigWta_Dijet_Mjj->SetBinError(1,0.8765736);
   sigWta_Dijet_Mjj->SetBinError(2,0.8367672);
   sigWta_Dijet_Mjj->SetBinError(3,0.510996);
   sigWta_Dijet_Mjj->SetBinError(4,0.2767248);
   sigWta_Dijet_Mjj->SetBinError(6,0.01392364);
   sigWta_Dijet_Mjj->SetEntries(78);

   ci = TColor::GetColor("#cc6600");
   sigWta_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#cc6600");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_Dijet_Mjj,"");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,0.02206686);
   sigWta_Dijet_Mjj->SetBinContent(2,1.21782);
   sigWta_Dijet_Mjj->SetBinContent(3,0.03787033);
   sigWta_Dijet_Mjj->SetBinContent(4,1.196697);
   sigWta_Dijet_Mjj->SetBinContent(5,0.01514764);
   sigWta_Dijet_Mjj->SetBinError(1,0.01617197);
   sigWta_Dijet_Mjj->SetBinError(2,1.194549);
   sigWta_Dijet_Mjj->SetBinError(3,0.02188967);
   sigWta_Dijet_Mjj->SetBinError(4,1.196697);
   sigWta_Dijet_Mjj->SetBinError(5,0.01514764);
   sigWta_Dijet_Mjj->SetEntries(27);

   ci = TColor::GetColor("#ffcc66");
   sigWta_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc66");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_Dijet_Mjj,"");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,18.4901);
   sigWta_Dijet_Mjj->SetBinContent(2,12.90498);
   sigWta_Dijet_Mjj->SetBinContent(3,9.348868);
   sigWta_Dijet_Mjj->SetBinContent(4,4.032015);
   sigWta_Dijet_Mjj->SetBinContent(5,3.33513);
   sigWta_Dijet_Mjj->SetBinContent(6,0.58815);
   sigWta_Dijet_Mjj->SetBinContent(7,3.400762);
   sigWta_Dijet_Mjj->SetBinError(1,3.158527);
   sigWta_Dijet_Mjj->SetBinError(2,2.831909);
   sigWta_Dijet_Mjj->SetBinError(3,2.176838);
   sigWta_Dijet_Mjj->SetBinError(4,1.201711);
   sigWta_Dijet_Mjj->SetBinError(5,1.268391);
   sigWta_Dijet_Mjj->SetBinError(6,0.2767904);
   sigWta_Dijet_Mjj->SetBinError(7,1.088095);
   sigWta_Dijet_Mjj->SetEntries(1909);

   ci = TColor::GetColor("#993300");
   sigWta_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#993300");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_Dijet_Mjj,"");
   h1->Draw("histsame");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(1,31);
   sigWta_Dijet_Mjj->SetBinContent(2,17);
   sigWta_Dijet_Mjj->SetBinContent(3,6);
   sigWta_Dijet_Mjj->SetBinContent(4,9);
   sigWta_Dijet_Mjj->SetBinContent(5,5);
   sigWta_Dijet_Mjj->SetBinContent(6,2);
   sigWta_Dijet_Mjj->SetBinContent(7,6);
   sigWta_Dijet_Mjj->SetBinError(1,5.567764);
   sigWta_Dijet_Mjj->SetBinError(2,4.123106);
   sigWta_Dijet_Mjj->SetBinError(3,2.44949);
   sigWta_Dijet_Mjj->SetBinError(4,3);
   sigWta_Dijet_Mjj->SetBinError(5,2.236068);
   sigWta_Dijet_Mjj->SetBinError(6,1.414214);
   sigWta_Dijet_Mjj->SetBinError(7,2.44949);
   sigWta_Dijet_Mjj->SetMinimum(0);
   sigWta_Dijet_Mjj->SetMaximum(43.4);
   sigWta_Dijet_Mjj->SetEntries(76);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->SetMarkerSize(0.8);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(999);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitle("Events");
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.095);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(0.85);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->Draw("P0E1same");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj->SetBinContent(3,1.678473);
   sigWta_Dijet_Mjj->SetBinContent(7,2.273738);
   sigWta_Dijet_Mjj->SetBinError(3,1.678473);
   sigWta_Dijet_Mjj->SetBinError(7,2.273738);
   sigWta_Dijet_Mjj->SetEntries(2);

   ci = TColor::GetColor("#ff0000");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetLineWidth(3);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->Draw("HISTsame");
   
   TH1D *sigWta_Dijet_Mjj = new TH1D("sigWta_Dijet_Mjj","Dijet_Mjj",6,1200,2160);

   ci = TColor::GetColor("#0000ff");
   sigWta_Dijet_Mjj->SetLineColor(ci);
   sigWta_Dijet_Mjj->SetLineStyle(0);
   sigWta_Dijet_Mjj->SetLineWidth(3);
   sigWta_Dijet_Mjj->SetMarkerStyle(20);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigWta_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj->Draw("HISTsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigWta_Dijet_Mjj","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","Top","F");

   ci = TColor::GetColor("#9999cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#9999cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","W#rightarrow e#nu","F");

   ci = TColor::GetColor("#cc6600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc6600");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","W#rightarrow#mu#nu","F");

   ci = TColor::GetColor("#ffcc66");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc66");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","W#rightarrow#tau#nu","F");

   ci = TColor::GetColor("#993300");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#993300");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","Signal (x1)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_Dijet_Mjj","gg#rightarrow H (x1)","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigWta_Dijet_Mjj__1 = new TH1D("sigWta_Dijet_Mjj__1","Dijet_Mjj",6,1200,2160);
   sigWta_Dijet_Mjj__1->SetBinContent(1,31);
   sigWta_Dijet_Mjj__1->SetBinContent(2,17);
   sigWta_Dijet_Mjj__1->SetBinContent(3,6);
   sigWta_Dijet_Mjj__1->SetBinContent(4,9);
   sigWta_Dijet_Mjj__1->SetBinContent(5,5);
   sigWta_Dijet_Mjj__1->SetBinContent(6,2);
   sigWta_Dijet_Mjj__1->SetBinContent(7,6);
   sigWta_Dijet_Mjj__1->SetBinError(1,5.567764);
   sigWta_Dijet_Mjj__1->SetBinError(2,4.123106);
   sigWta_Dijet_Mjj__1->SetBinError(3,2.44949);
   sigWta_Dijet_Mjj__1->SetBinError(4,3);
   sigWta_Dijet_Mjj__1->SetBinError(5,2.236068);
   sigWta_Dijet_Mjj__1->SetBinError(6,1.414214);
   sigWta_Dijet_Mjj__1->SetBinError(7,2.44949);
   sigWta_Dijet_Mjj__1->SetMinimum(0);
   sigWta_Dijet_Mjj__1->SetMaximum(43.4);
   sigWta_Dijet_Mjj__1->SetEntries(76);
   sigWta_Dijet_Mjj__1->SetDirectory(0);
   sigWta_Dijet_Mjj__1->SetLineStyle(0);
   sigWta_Dijet_Mjj__1->SetMarkerStyle(20);
   sigWta_Dijet_Mjj__1->SetMarkerSize(0.8);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigWta_Dijet_Mjj__1->GetXaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetLabelOffset(999);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetLabelSize(0);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetTitleOffset(0.9);
   sigWta_Dijet_Mjj__1->GetXaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj__1->GetYaxis()->SetTitle("Events");
   sigWta_Dijet_Mjj__1->GetYaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj__1->GetYaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj__1->GetYaxis()->SetLabelSize(0.06);
   sigWta_Dijet_Mjj__1->GetYaxis()->SetTitleSize(0.095);
   sigWta_Dijet_Mjj__1->GetYaxis()->SetTitleOffset(0.85);
   sigWta_Dijet_Mjj__1->GetZaxis()->SetLabelFont(42);
   sigWta_Dijet_Mjj__1->GetZaxis()->SetLabelOffset(0.007);
   sigWta_Dijet_Mjj__1->GetZaxis()->SetLabelSize(0.05);
   sigWta_Dijet_Mjj__1->GetZaxis()->SetTitleSize(0.06);
   sigWta_Dijet_Mjj__1->GetZaxis()->SetTitleFont(42);
   sigWta_Dijet_Mjj__1->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(925.7143,-1.914893,2297.143,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",6,1200,2160);
   h1_num->SetBinContent(1,1.342684);
   h1_num->SetBinContent(2,0.9019943);
   h1_num->SetBinContent(3,0.4724818);
   h1_num->SetBinContent(4,1.285261);
   h1_num->SetBinContent(5,1.341439);
   h1_num->SetBinContent(6,1.565613);
   h1_num->SetBinContent(7,1.764311);
   h1_num->SetBinError(1,0.3173738);
   h1_num->SetBinError(2,0.2760341);
   h1_num->SetBinError(3,0.2159624);
   h1_num->SetBinError(4,0.5555155);
   h1_num->SetBinError(5,0.7659725);
   h1_num->SetBinError(6,1.374794);
   h1_num->SetBinError(7,0.9151291);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(15.86637);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("M_{jj} [GeV]");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(1200,1,2160,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
