{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 14:57:34 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-50,-0.9172414,650,29.65747);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,1);
   sigWta_metNoMuon->SetBinContent(2,19);
   sigWta_metNoMuon->SetBinContent(3,18);
   sigWta_metNoMuon->SetBinContent(4,11);
   sigWta_metNoMuon->SetBinContent(5,13);
   sigWta_metNoMuon->SetBinContent(6,6);
   sigWta_metNoMuon->SetBinContent(7,6);
   sigWta_metNoMuon->SetBinContent(8,1);
   sigWta_metNoMuon->SetBinContent(10,1);
   sigWta_metNoMuon->SetBinError(1,1);
   sigWta_metNoMuon->SetBinError(2,4.358899);
   sigWta_metNoMuon->SetBinError(3,4.242641);
   sigWta_metNoMuon->SetBinError(4,3.316625);
   sigWta_metNoMuon->SetBinError(5,3.605551);
   sigWta_metNoMuon->SetBinError(6,2.44949);
   sigWta_metNoMuon->SetBinError(7,2.44949);
   sigWta_metNoMuon->SetBinError(8,1);
   sigWta_metNoMuon->SetBinError(10,1);
   sigWta_metNoMuon->SetMinimum(0);
   sigWta_metNoMuon->SetMaximum(26.6);
   sigWta_metNoMuon->SetEntries(76);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->SetMarkerSize(0.8);
   sigWta_metNoMuon->GetXaxis()->SetTitle("MET [GeV]");
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(999);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetTitle("Events");
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.095);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(0.85);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigWta_metNoMuon->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_2 = new TH1F("h1_stack_2","h1",16,90,580);
   h1_stack_2->SetMinimum(0);
   h1_stack_2->SetMaximum(16.59528);
   h1_stack_2->SetDirectory(0);
   h1_stack_2->SetStats(0);
   h1_stack_2->SetLineStyle(0);
   h1_stack_2->SetMarkerStyle(20);
   h1_stack_2->GetXaxis()->SetNdivisions(505);
   h1_stack_2->GetXaxis()->SetLabelFont(42);
   h1_stack_2->GetXaxis()->SetLabelOffset(999);
   h1_stack_2->GetXaxis()->SetLabelSize(0);
   h1_stack_2->GetXaxis()->SetTitleSize(0.06);
   h1_stack_2->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_2->GetXaxis()->SetTitleFont(42);
   h1_stack_2->GetYaxis()->SetNdivisions(505);
   h1_stack_2->GetYaxis()->SetLabelFont(42);
   h1_stack_2->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_2->GetYaxis()->SetLabelSize(0.06);
   h1_stack_2->GetYaxis()->SetTitleSize(0.095);
   h1_stack_2->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_2->GetZaxis()->SetNdivisions(505);
   h1_stack_2->GetZaxis()->SetLabelFont(42);
   h1_stack_2->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_2->GetZaxis()->SetLabelSize(0.03);
   h1_stack_2->GetZaxis()->SetTitleSize(0.06);
   h1_stack_2->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_2);
   
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,0.9858691);
   sigWta_metNoMuon->SetBinContent(2,1.799665);
   sigWta_metNoMuon->SetBinContent(3,2.943676);
   sigWta_metNoMuon->SetBinContent(4,2.715844);
   sigWta_metNoMuon->SetBinContent(5,2.442786);
   sigWta_metNoMuon->SetBinContent(6,0.372188);
   sigWta_metNoMuon->SetBinContent(7,0.4863923);
   sigWta_metNoMuon->SetBinError(1,0.822614);
   sigWta_metNoMuon->SetBinError(2,1.142332);
   sigWta_metNoMuon->SetBinError(3,1.264837);
   sigWta_metNoMuon->SetBinError(4,1.367874);
   sigWta_metNoMuon->SetBinError(5,1.132893);
   sigWta_metNoMuon->SetBinError(6,0.372188);
   sigWta_metNoMuon->SetBinError(7,0.4863923);
   sigWta_metNoMuon->SetEntries(22);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#9999cc");
   sigWta_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#9999cc");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_metNoMuon,"");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,0.02847289);
   sigWta_metNoMuon->SetBinContent(2,0.1161903);
   sigWta_metNoMuon->SetBinContent(3,0.07920578);
   sigWta_metNoMuon->SetBinContent(4,0.2071396);
   sigWta_metNoMuon->SetBinContent(6,0.07265084);
   sigWta_metNoMuon->SetBinError(1,0.02847289);
   sigWta_metNoMuon->SetBinError(2,0.09193336);
   sigWta_metNoMuon->SetBinError(3,0.07556407);
   sigWta_metNoMuon->SetBinError(4,0.1318695);
   sigWta_metNoMuon->SetBinError(6,0.07265084);
   sigWta_metNoMuon->SetEntries(9);

   ci = TColor::GetColor("#669966");
   sigWta_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_metNoMuon,"");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,0.01138886);
   sigWta_metNoMuon->SetBinContent(2,0.5434417);
   sigWta_metNoMuon->SetBinContent(3,1.093739);
   sigWta_metNoMuon->SetBinContent(4,0.331461);
   sigWta_metNoMuon->SetBinContent(5,0.836264);
   sigWta_metNoMuon->SetBinContent(8,0.3861615);
   sigWta_metNoMuon->SetBinError(1,0.01138886);
   sigWta_metNoMuon->SetBinError(2,0.5111492);
   sigWta_metNoMuon->SetBinError(3,0.7869306);
   sigWta_metNoMuon->SetBinError(4,0.2780772);
   sigWta_metNoMuon->SetBinError(5,0.836264);
   sigWta_metNoMuon->SetBinError(8,0.3861615);
   sigWta_metNoMuon->SetEntries(78);

   ci = TColor::GetColor("#cc6600");
   sigWta_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#cc6600");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_metNoMuon,"");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(2,1.206252);
   sigWta_metNoMuon->SetBinContent(3,0.03141682);
   sigWta_metNoMuon->SetBinContent(4,0.01403839);
   sigWta_metNoMuon->SetBinContent(5,0.02791069);
   sigWta_metNoMuon->SetBinContent(9,1.209984);
   sigWta_metNoMuon->SetBinError(2,1.19449);
   sigWta_metNoMuon->SetBinError(3,0.01859665);
   sigWta_metNoMuon->SetBinError(4,0.01403839);
   sigWta_metNoMuon->SetBinError(5,0.01980774);
   sigWta_metNoMuon->SetBinError(9,1.196771);
   sigWta_metNoMuon->SetEntries(27);

   ci = TColor::GetColor("#ffcc66");
   sigWta_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc66");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_metNoMuon,"");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,3.924282);
   sigWta_metNoMuon->SetBinContent(2,12.13947);
   sigWta_metNoMuon->SetBinContent(3,8.64479);
   sigWta_metNoMuon->SetBinContent(4,6.335733);
   sigWta_metNoMuon->SetBinContent(5,7.164995);
   sigWta_metNoMuon->SetBinContent(6,3.312102);
   sigWta_metNoMuon->SetBinContent(7,3.333468);
   sigWta_metNoMuon->SetBinContent(8,3.292366);
   sigWta_metNoMuon->SetBinContent(9,1.243601);
   sigWta_metNoMuon->SetBinContent(10,1.519753);
   sigWta_metNoMuon->SetBinContent(11,0.05119241);
   sigWta_metNoMuon->SetBinContent(12,0.3677375);
   sigWta_metNoMuon->SetBinContent(13,0.03484218);
   sigWta_metNoMuon->SetBinContent(14,0.4004686);
   sigWta_metNoMuon->SetBinContent(17,0.3351947);
   sigWta_metNoMuon->SetBinError(1,1.439303);
   sigWta_metNoMuon->SetBinError(2,2.441934);
   sigWta_metNoMuon->SetBinError(3,1.994899);
   sigWta_metNoMuon->SetBinError(4,1.666828);
   sigWta_metNoMuon->SetBinError(5,2.296628);
   sigWta_metNoMuon->SetBinError(6,1.069545);
   sigWta_metNoMuon->SetBinError(7,1.423541);
   sigWta_metNoMuon->SetBinError(8,1.45921);
   sigWta_metNoMuon->SetBinError(9,0.6641633);
   sigWta_metNoMuon->SetBinError(10,0.9319267);
   sigWta_metNoMuon->SetBinError(11,0.02374537);
   sigWta_metNoMuon->SetBinError(12,0.3564563);
   sigWta_metNoMuon->SetBinError(13,0.02089656);
   sigWta_metNoMuon->SetBinError(14,0.3624039);
   sigWta_metNoMuon->SetBinError(17,0.3351947);
   sigWta_metNoMuon->SetEntries(1909);

   ci = TColor::GetColor("#993300");
   sigWta_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#993300");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWta_metNoMuon,"");
   h1->Draw("histsame");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(1,1);
   sigWta_metNoMuon->SetBinContent(2,19);
   sigWta_metNoMuon->SetBinContent(3,18);
   sigWta_metNoMuon->SetBinContent(4,11);
   sigWta_metNoMuon->SetBinContent(5,13);
   sigWta_metNoMuon->SetBinContent(6,6);
   sigWta_metNoMuon->SetBinContent(7,6);
   sigWta_metNoMuon->SetBinContent(8,1);
   sigWta_metNoMuon->SetBinContent(10,1);
   sigWta_metNoMuon->SetBinError(1,1);
   sigWta_metNoMuon->SetBinError(2,4.358899);
   sigWta_metNoMuon->SetBinError(3,4.242641);
   sigWta_metNoMuon->SetBinError(4,3.316625);
   sigWta_metNoMuon->SetBinError(5,3.605551);
   sigWta_metNoMuon->SetBinError(6,2.44949);
   sigWta_metNoMuon->SetBinError(7,2.44949);
   sigWta_metNoMuon->SetBinError(8,1);
   sigWta_metNoMuon->SetBinError(10,1);
   sigWta_metNoMuon->SetMinimum(0);
   sigWta_metNoMuon->SetMaximum(26.6);
   sigWta_metNoMuon->SetEntries(76);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->SetMarkerSize(0.8);
   sigWta_metNoMuon->GetXaxis()->SetTitle("MET [GeV]");
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(999);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetTitle("Events");
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.095);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(0.85);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigWta_metNoMuon->Draw("P0E1same");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);
   sigWta_metNoMuon->SetBinContent(2,1.678473);
   sigWta_metNoMuon->SetBinContent(5,2.273738);
   sigWta_metNoMuon->SetBinError(2,1.678473);
   sigWta_metNoMuon->SetBinError(5,2.273738);
   sigWta_metNoMuon->SetEntries(2);

   ci = TColor::GetColor("#ff0000");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetLineWidth(3);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigWta_metNoMuon->Draw("HISTsame");
   
   TH1D *sigWta_metNoMuon = new TH1D("sigWta_metNoMuon","metNoMuon",16,90,580);

   ci = TColor::GetColor("#0000ff");
   sigWta_metNoMuon->SetLineColor(ci);
   sigWta_metNoMuon->SetLineStyle(0);
   sigWta_metNoMuon->SetLineWidth(3);
   sigWta_metNoMuon->SetMarkerStyle(20);
   sigWta_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigWta_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigWta_metNoMuon->Draw("HISTsame");
   
   TLegend *leg = new TLegend(0.7,0.55,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigWta_metNoMuon","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","Top","F");

   ci = TColor::GetColor("#9999cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#9999cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","W#rightarrow e#nu","F");

   ci = TColor::GetColor("#cc6600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc6600");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","W#rightarrow#mu#nu","F");

   ci = TColor::GetColor("#ffcc66");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc66");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","W#rightarrow#tau#nu","F");

   ci = TColor::GetColor("#993300");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#993300");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","Signal (x1)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWta_metNoMuon","gg#rightarrow H (x1)","L");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigWta_metNoMuon__2 = new TH1D("sigWta_metNoMuon__2","metNoMuon",16,90,580);
   sigWta_metNoMuon__2->SetBinContent(1,1);
   sigWta_metNoMuon__2->SetBinContent(2,19);
   sigWta_metNoMuon__2->SetBinContent(3,18);
   sigWta_metNoMuon__2->SetBinContent(4,11);
   sigWta_metNoMuon__2->SetBinContent(5,13);
   sigWta_metNoMuon__2->SetBinContent(6,6);
   sigWta_metNoMuon__2->SetBinContent(7,6);
   sigWta_metNoMuon__2->SetBinContent(8,1);
   sigWta_metNoMuon__2->SetBinContent(10,1);
   sigWta_metNoMuon__2->SetBinError(1,1);
   sigWta_metNoMuon__2->SetBinError(2,4.358899);
   sigWta_metNoMuon__2->SetBinError(3,4.242641);
   sigWta_metNoMuon__2->SetBinError(4,3.316625);
   sigWta_metNoMuon__2->SetBinError(5,3.605551);
   sigWta_metNoMuon__2->SetBinError(6,2.44949);
   sigWta_metNoMuon__2->SetBinError(7,2.44949);
   sigWta_metNoMuon__2->SetBinError(8,1);
   sigWta_metNoMuon__2->SetBinError(10,1);
   sigWta_metNoMuon__2->SetMinimum(0);
   sigWta_metNoMuon__2->SetMaximum(26.6);
   sigWta_metNoMuon__2->SetEntries(76);
   sigWta_metNoMuon__2->SetDirectory(0);
   sigWta_metNoMuon__2->SetLineStyle(0);
   sigWta_metNoMuon__2->SetMarkerStyle(20);
   sigWta_metNoMuon__2->SetMarkerSize(0.8);
   sigWta_metNoMuon__2->GetXaxis()->SetTitle("MET [GeV]");
   sigWta_metNoMuon__2->GetXaxis()->SetLabelFont(42);
   sigWta_metNoMuon__2->GetXaxis()->SetLabelOffset(999);
   sigWta_metNoMuon__2->GetXaxis()->SetLabelSize(0);
   sigWta_metNoMuon__2->GetXaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon__2->GetXaxis()->SetTitleOffset(0.9);
   sigWta_metNoMuon__2->GetXaxis()->SetTitleFont(42);
   sigWta_metNoMuon__2->GetYaxis()->SetTitle("Events");
   sigWta_metNoMuon__2->GetYaxis()->SetLabelFont(42);
   sigWta_metNoMuon__2->GetYaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon__2->GetYaxis()->SetLabelSize(0.06);
   sigWta_metNoMuon__2->GetYaxis()->SetTitleSize(0.095);
   sigWta_metNoMuon__2->GetYaxis()->SetTitleOffset(0.85);
   sigWta_metNoMuon__2->GetZaxis()->SetLabelFont(42);
   sigWta_metNoMuon__2->GetZaxis()->SetLabelOffset(0.007);
   sigWta_metNoMuon__2->GetZaxis()->SetLabelSize(0.05);
   sigWta_metNoMuon__2->GetZaxis()->SetTitleSize(0.06);
   sigWta_metNoMuon__2->GetZaxis()->SetTitleFont(42);
   sigWta_metNoMuon__2->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(-50,-1.914893,650,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",16,90,580);
   h1_num->SetBinContent(1,0.2020197);
   h1_num->SetBinContent(2,1.202149);
   h1_num->SetBinContent(3,1.407038);
   h1_num->SetBinContent(4,1.14533);
   h1_num->SetBinContent(5,1.241411);
   h1_num->SetBinContent(6,1.597044);
   h1_num->SetBinContent(7,1.570738);
   h1_num->SetBinContent(8,0.2718479);
   h1_num->SetBinContent(10,0.6580015);
   h1_num->SetBinError(1,0.2130519);
   h1_num->SetBinError(2,0.3576641);
   h1_num->SetBinError(3,0.4301692);
   h1_num->SetBinError(4,0.4321144);
   h1_num->SetBinError(5,0.4696167);
   h1_num->SetBinError(6,0.8110412);
   h1_num->SetBinError(7,0.8909867);
   h1_num->SetBinError(8,0.2938446);
   h1_num->SetBinError(10,0.7718628);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(29.80212);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("MET [GeV]");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(90,1,580,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
