{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Wed Nov 18 18:37:36 2015) by ROOT version5.34/18
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(0,0,1,1);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.15);
   c1_n2->SetRightMargin(0.15);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.15);
   c1_n2->SetFrameFillStyle(0);
   c1_n2->SetFrameBorderMode(0);
   
   TH1D *LeadDijet_DPhi = new TH1D("LeadDijet_DPhi","LeadDijet_DPhi",64,0,3.141593);
   LeadDijet_DPhi->SetBinContent(1,65);
   LeadDijet_DPhi->SetBinContent(2,37);
   LeadDijet_DPhi->SetBinContent(3,48);
   LeadDijet_DPhi->SetBinContent(4,48);
   LeadDijet_DPhi->SetBinContent(5,54);
   LeadDijet_DPhi->SetBinContent(6,59);
   LeadDijet_DPhi->SetBinContent(7,67);
   LeadDijet_DPhi->SetBinContent(8,50);
   LeadDijet_DPhi->SetBinContent(9,45);
   LeadDijet_DPhi->SetBinContent(10,74);
   LeadDijet_DPhi->SetBinContent(11,55);
   LeadDijet_DPhi->SetBinContent(12,70);
   LeadDijet_DPhi->SetBinContent(13,63);
   LeadDijet_DPhi->SetBinContent(14,60);
   LeadDijet_DPhi->SetBinContent(15,66);
   LeadDijet_DPhi->SetBinContent(16,62);
   LeadDijet_DPhi->SetBinContent(17,72);
   LeadDijet_DPhi->SetBinContent(18,62);
   LeadDijet_DPhi->SetBinContent(19,54);
   LeadDijet_DPhi->SetBinContent(20,82);
   LeadDijet_DPhi->SetBinContent(21,67);
   LeadDijet_DPhi->SetBinContent(22,62);
   LeadDijet_DPhi->SetBinContent(23,65);
   LeadDijet_DPhi->SetBinContent(24,74);
   LeadDijet_DPhi->SetBinContent(25,78);
   LeadDijet_DPhi->SetBinContent(26,78);
   LeadDijet_DPhi->SetBinContent(27,74);
   LeadDijet_DPhi->SetBinContent(28,100);
   LeadDijet_DPhi->SetBinContent(29,98);
   LeadDijet_DPhi->SetBinContent(30,101);
   LeadDijet_DPhi->SetBinContent(31,93);
   LeadDijet_DPhi->SetBinContent(32,97);
   LeadDijet_DPhi->SetBinContent(33,103);
   LeadDijet_DPhi->SetBinContent(34,112);
   LeadDijet_DPhi->SetBinContent(35,112);
   LeadDijet_DPhi->SetBinContent(36,123);
   LeadDijet_DPhi->SetBinContent(37,124);
   LeadDijet_DPhi->SetBinContent(38,123);
   LeadDijet_DPhi->SetBinContent(39,154);
   LeadDijet_DPhi->SetBinContent(40,181);
   LeadDijet_DPhi->SetBinContent(41,191);
   LeadDijet_DPhi->SetBinContent(42,182);
   LeadDijet_DPhi->SetBinContent(43,211);
   LeadDijet_DPhi->SetBinContent(44,165);
   LeadDijet_DPhi->SetEntries(3961);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   LeadDijet_DPhi->SetLineColor(ci);
   LeadDijet_DPhi->GetXaxis()->SetTitle("Lead Generator Dijet #Delta#phi");
   LeadDijet_DPhi->GetXaxis()->SetRange(1,128);
   LeadDijet_DPhi->GetXaxis()->SetLabelFont(42);
   LeadDijet_DPhi->GetXaxis()->SetLabelSize(0.035);
   LeadDijet_DPhi->GetXaxis()->SetTitleSize(0.035);
   LeadDijet_DPhi->GetXaxis()->SetTitleFont(42);
   LeadDijet_DPhi->GetYaxis()->SetTitle("Events");
   LeadDijet_DPhi->GetYaxis()->SetLabelFont(42);
   LeadDijet_DPhi->GetYaxis()->SetLabelSize(0.035);
   LeadDijet_DPhi->GetYaxis()->SetTitleSize(0.035);
   LeadDijet_DPhi->GetYaxis()->SetTitleOffset(1.75);
   LeadDijet_DPhi->GetYaxis()->SetTitleFont(42);
   LeadDijet_DPhi->GetZaxis()->SetLabelFont(42);
   LeadDijet_DPhi->GetZaxis()->SetLabelSize(0.035);
   LeadDijet_DPhi->GetZaxis()->SetTitleSize(0.035);
   LeadDijet_DPhi->GetZaxis()->SetTitleFont(42);
   LeadDijet_DPhi->Draw("");
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
