{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 09:06:37 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(-50,-0.1931034,650,6.243678);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigZmumu_metNoMuon = new TH1D("sigZmumu_metNoMuon","metNoMuon",16,90,580);
   sigZmumu_metNoMuon->SetBinContent(2,1);
   sigZmumu_metNoMuon->SetBinContent(3,3);
   sigZmumu_metNoMuon->SetBinContent(4,1);
   sigZmumu_metNoMuon->SetBinContent(5,4);
   sigZmumu_metNoMuon->SetBinContent(6,3);
   sigZmumu_metNoMuon->SetBinContent(7,2);
   sigZmumu_metNoMuon->SetBinContent(10,3);
   sigZmumu_metNoMuon->SetBinContent(12,1);
   sigZmumu_metNoMuon->SetBinError(2,1);
   sigZmumu_metNoMuon->SetBinError(3,1.732051);
   sigZmumu_metNoMuon->SetBinError(4,1);
   sigZmumu_metNoMuon->SetBinError(5,2);
   sigZmumu_metNoMuon->SetBinError(6,1.732051);
   sigZmumu_metNoMuon->SetBinError(7,1.414214);
   sigZmumu_metNoMuon->SetBinError(10,1.732051);
   sigZmumu_metNoMuon->SetBinError(12,1);
   sigZmumu_metNoMuon->SetMinimum(0);
   sigZmumu_metNoMuon->SetMaximum(5.6);
   sigZmumu_metNoMuon->SetEntries(18);
   sigZmumu_metNoMuon->SetLineStyle(0);
   sigZmumu_metNoMuon->SetMarkerStyle(20);
   sigZmumu_metNoMuon->SetMarkerSize(0.8);
   sigZmumu_metNoMuon->GetXaxis()->SetTitle("MET [GeV]");
   sigZmumu_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_4 = new TH1F("h1_stack_4","h1",16,90,580);
   h1_stack_4->SetMinimum(-5.551115e-17);
   h1_stack_4->SetMaximum(3.320065);
   h1_stack_4->SetDirectory(0);
   h1_stack_4->SetStats(0);
   h1_stack_4->SetLineStyle(0);
   h1_stack_4->SetMarkerStyle(20);
   h1_stack_4->GetXaxis()->SetNdivisions(505);
   h1_stack_4->GetXaxis()->SetLabelFont(42);
   h1_stack_4->GetXaxis()->SetLabelOffset(999);
   h1_stack_4->GetXaxis()->SetLabelSize(0);
   h1_stack_4->GetXaxis()->SetTitleSize(0.06);
   h1_stack_4->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_4->GetXaxis()->SetTitleFont(42);
   h1_stack_4->GetYaxis()->SetNdivisions(505);
   h1_stack_4->GetYaxis()->SetLabelFont(42);
   h1_stack_4->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_4->GetYaxis()->SetLabelSize(0.06);
   h1_stack_4->GetYaxis()->SetTitleSize(0.095);
   h1_stack_4->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_4->GetZaxis()->SetNdivisions(505);
   h1_stack_4->GetZaxis()->SetLabelFont(42);
   h1_stack_4->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_4->GetZaxis()->SetLabelSize(0.03);
   h1_stack_4->GetZaxis()->SetTitleSize(0.06);
   h1_stack_4->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_4);
   
   
   TH1D *sigZmumu_metNoMuon = new TH1D("sigZmumu_metNoMuon","metNoMuon",16,90,580);
   sigZmumu_metNoMuon->SetBinContent(2,0.05096845);
   sigZmumu_metNoMuon->SetBinContent(6,0.09060062);
   sigZmumu_metNoMuon->SetBinError(2,0.05096845);
   sigZmumu_metNoMuon->SetBinError(6,0.09060062);
   sigZmumu_metNoMuon->SetEntries(3);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#669966");
   sigZmumu_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigZmumu_metNoMuon->SetLineColor(ci);
   sigZmumu_metNoMuon->SetLineStyle(0);
   sigZmumu_metNoMuon->SetMarkerStyle(20);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon,"");
   
   TH1D *sigZmumu_metNoMuon = new TH1D("sigZmumu_metNoMuon","metNoMuon",16,90,580);
   sigZmumu_metNoMuon->SetBinContent(1,0.05254427);
   sigZmumu_metNoMuon->SetBinContent(2,0.3368234);
   sigZmumu_metNoMuon->SetBinContent(3,0.704387);
   sigZmumu_metNoMuon->SetBinContent(4,0.7472882);
   sigZmumu_metNoMuon->SetBinContent(5,0.7568168);
   sigZmumu_metNoMuon->SetBinContent(6,0.8147928);
   sigZmumu_metNoMuon->SetBinContent(7,0.6394123);
   sigZmumu_metNoMuon->SetBinContent(8,0.4068909);
   sigZmumu_metNoMuon->SetBinContent(9,0.3112281);
   sigZmumu_metNoMuon->SetBinContent(10,0.2769284);
   sigZmumu_metNoMuon->SetBinContent(11,0.08936601);
   sigZmumu_metNoMuon->SetBinContent(12,0.1427943);
   sigZmumu_metNoMuon->SetBinContent(13,0.09353843);
   sigZmumu_metNoMuon->SetBinContent(14,0.03750797);
   sigZmumu_metNoMuon->SetBinContent(15,0.01087806);
   sigZmumu_metNoMuon->SetBinContent(16,0.01937445);
   sigZmumu_metNoMuon->SetBinContent(17,0.02586788);
   sigZmumu_metNoMuon->SetBinError(1,0.01574448);
   sigZmumu_metNoMuon->SetBinError(2,0.04349133);
   sigZmumu_metNoMuon->SetBinError(3,0.0678385);
   sigZmumu_metNoMuon->SetBinError(4,0.06998069);
   sigZmumu_metNoMuon->SetBinError(5,0.07107543);
   sigZmumu_metNoMuon->SetBinError(6,0.07585683);
   sigZmumu_metNoMuon->SetBinError(7,0.06856378);
   sigZmumu_metNoMuon->SetBinError(8,0.05345657);
   sigZmumu_metNoMuon->SetBinError(9,0.04686329);
   sigZmumu_metNoMuon->SetBinError(10,0.04341592);
   sigZmumu_metNoMuon->SetBinError(11,0.02366993);
   sigZmumu_metNoMuon->SetBinError(12,0.03016578);
   sigZmumu_metNoMuon->SetBinError(13,0.02521004);
   sigZmumu_metNoMuon->SetBinError(14,0.01520895);
   sigZmumu_metNoMuon->SetBinError(15,0.01087806);
   sigZmumu_metNoMuon->SetBinError(16,0.01119718);
   sigZmumu_metNoMuon->SetBinError(17,0.0129499);
   sigZmumu_metNoMuon->SetEntries(1161);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_metNoMuon->SetLineColor(ci);
   sigZmumu_metNoMuon->SetLineStyle(0);
   sigZmumu_metNoMuon->SetMarkerStyle(20);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon,"");
   
   TH1D *sigZmumu_metNoMuon = new TH1D("sigZmumu_metNoMuon","metNoMuon",16,90,580);
   sigZmumu_metNoMuon->SetBinContent(1,0.0444929);
   sigZmumu_metNoMuon->SetBinContent(2,1.762339);
   sigZmumu_metNoMuon->SetBinContent(3,1.59682);
   sigZmumu_metNoMuon->SetBinContent(4,2.256685);
   sigZmumu_metNoMuon->SetBinContent(5,1.868231);
   sigZmumu_metNoMuon->SetBinContent(6,2.061849);
   sigZmumu_metNoMuon->SetBinContent(7,1.326862);
   sigZmumu_metNoMuon->SetBinContent(8,0.6760255);
   sigZmumu_metNoMuon->SetBinContent(10,0.4741521);
   sigZmumu_metNoMuon->SetBinContent(11,0.3261041);
   sigZmumu_metNoMuon->SetBinError(1,0.0444929);
   sigZmumu_metNoMuon->SetBinError(2,0.6497153);
   sigZmumu_metNoMuon->SetBinError(3,0.7351106);
   sigZmumu_metNoMuon->SetBinError(4,0.9052817);
   sigZmumu_metNoMuon->SetBinError(5,0.8365447);
   sigZmumu_metNoMuon->SetBinError(6,0.8433199);
   sigZmumu_metNoMuon->SetBinError(7,0.6418818);
   sigZmumu_metNoMuon->SetBinError(8,0.4780408);
   sigZmumu_metNoMuon->SetBinError(10,0.4741521);
   sigZmumu_metNoMuon->SetBinError(11,0.3261041);
   sigZmumu_metNoMuon->SetEntries(75);

   ci = TColor::GetColor("#006699");
   sigZmumu_metNoMuon->SetFillColor(ci);

   ci = TColor::GetColor("#006699");
   sigZmumu_metNoMuon->SetLineColor(ci);
   sigZmumu_metNoMuon->SetLineStyle(0);
   sigZmumu_metNoMuon->SetMarkerStyle(20);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon,"");
   h1->Draw("histsame");
   
   TH1D *sigZmumu_metNoMuon = new TH1D("sigZmumu_metNoMuon","metNoMuon",16,90,580);
   sigZmumu_metNoMuon->SetBinContent(2,1);
   sigZmumu_metNoMuon->SetBinContent(3,3);
   sigZmumu_metNoMuon->SetBinContent(4,1);
   sigZmumu_metNoMuon->SetBinContent(5,4);
   sigZmumu_metNoMuon->SetBinContent(6,3);
   sigZmumu_metNoMuon->SetBinContent(7,2);
   sigZmumu_metNoMuon->SetBinContent(10,3);
   sigZmumu_metNoMuon->SetBinContent(12,1);
   sigZmumu_metNoMuon->SetBinError(2,1);
   sigZmumu_metNoMuon->SetBinError(3,1.732051);
   sigZmumu_metNoMuon->SetBinError(4,1);
   sigZmumu_metNoMuon->SetBinError(5,2);
   sigZmumu_metNoMuon->SetBinError(6,1.732051);
   sigZmumu_metNoMuon->SetBinError(7,1.414214);
   sigZmumu_metNoMuon->SetBinError(10,1.732051);
   sigZmumu_metNoMuon->SetBinError(12,1);
   sigZmumu_metNoMuon->SetMinimum(0);
   sigZmumu_metNoMuon->SetMaximum(5.6);
   sigZmumu_metNoMuon->SetEntries(18);
   sigZmumu_metNoMuon->SetLineStyle(0);
   sigZmumu_metNoMuon->SetMarkerStyle(20);
   sigZmumu_metNoMuon->SetMarkerSize(0.8);
   sigZmumu_metNoMuon->GetXaxis()->SetTitle("MET [GeV]");
   sigZmumu_metNoMuon->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon->Draw("P0E1same");
   
   TLegend *leg = new TLegend(0.55,0.7,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigZmumu_metNoMuon","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon","Z#rightarrow#nu#nu EWK","F");

   ci = TColor::GetColor("#0066cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0066cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon","Z#rightarrow#nu#nu QCD","F");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006699");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigZmumu_metNoMuon__4 = new TH1D("sigZmumu_metNoMuon__4","metNoMuon",16,90,580);
   sigZmumu_metNoMuon__4->SetBinContent(2,1);
   sigZmumu_metNoMuon__4->SetBinContent(3,3);
   sigZmumu_metNoMuon__4->SetBinContent(4,1);
   sigZmumu_metNoMuon__4->SetBinContent(5,4);
   sigZmumu_metNoMuon__4->SetBinContent(6,3);
   sigZmumu_metNoMuon__4->SetBinContent(7,2);
   sigZmumu_metNoMuon__4->SetBinContent(10,3);
   sigZmumu_metNoMuon__4->SetBinContent(12,1);
   sigZmumu_metNoMuon__4->SetBinError(2,1);
   sigZmumu_metNoMuon__4->SetBinError(3,1.732051);
   sigZmumu_metNoMuon__4->SetBinError(4,1);
   sigZmumu_metNoMuon__4->SetBinError(5,2);
   sigZmumu_metNoMuon__4->SetBinError(6,1.732051);
   sigZmumu_metNoMuon__4->SetBinError(7,1.414214);
   sigZmumu_metNoMuon__4->SetBinError(10,1.732051);
   sigZmumu_metNoMuon__4->SetBinError(12,1);
   sigZmumu_metNoMuon__4->SetMinimum(0);
   sigZmumu_metNoMuon__4->SetMaximum(5.6);
   sigZmumu_metNoMuon__4->SetEntries(18);
   sigZmumu_metNoMuon__4->SetDirectory(0);
   sigZmumu_metNoMuon__4->SetLineStyle(0);
   sigZmumu_metNoMuon__4->SetMarkerStyle(20);
   sigZmumu_metNoMuon__4->SetMarkerSize(0.8);
   sigZmumu_metNoMuon__4->GetXaxis()->SetTitle("MET [GeV]");
   sigZmumu_metNoMuon__4->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon__4->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon__4->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon__4->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon__4->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon__4->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon__4->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon__4->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon__4->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon__4->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon__4->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon__4->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon__4->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon__4->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon__4->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon__4->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon__4->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon__4->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(-50,-1.914893,650,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",16,90,580);
   h1_num->SetBinContent(2,0.465088);
   h1_num->SetBinContent(3,1.303664);
   h1_num->SetBinContent(4,0.3328925);
   h1_num->SetBinContent(5,1.523782);
   h1_num->SetBinContent(6,1.01104);
   h1_num->SetBinContent(7,1.017152);
   h1_num->SetBinContent(10,3.994246);
   h1_num->SetBinContent(12,7.003079);
   h1_num->SetBinError(2,0.4860738);
   h1_num->SetBinError(3,0.8610578);
   h1_num->SetBinError(4,0.3477669);
   h1_num->SetBinError(5,0.904424);
   h1_num->SetBinError(6,0.6518616);
   h1_num->SetBinError(7,0.7929758);
   h1_num->SetBinError(10,3.424832);
   h1_num->SetBinError(12,7.15764);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(4.205172);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("MET [GeV]");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(90,1,580,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
