{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 09:06:37 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(2,-0.2896552,12,9.365517);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigZmumu_metNoMuon_Sig = new TH1D("sigZmumu_metNoMuon_Sig","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig->SetBinContent(1,3);
   sigZmumu_metNoMuon_Sig->SetBinContent(2,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(3,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(4,6);
   sigZmumu_metNoMuon_Sig->SetBinContent(5,1);
   sigZmumu_metNoMuon_Sig->SetBinContent(6,1);
   sigZmumu_metNoMuon_Sig->SetBinContent(7,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(8,1);
   sigZmumu_metNoMuon_Sig->SetBinError(1,1.732051);
   sigZmumu_metNoMuon_Sig->SetBinError(2,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(3,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(4,2.44949);
   sigZmumu_metNoMuon_Sig->SetBinError(5,1);
   sigZmumu_metNoMuon_Sig->SetBinError(6,1);
   sigZmumu_metNoMuon_Sig->SetBinError(7,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(8,1);
   sigZmumu_metNoMuon_Sig->SetMinimum(0);
   sigZmumu_metNoMuon_Sig->SetMaximum(8.4);
   sigZmumu_metNoMuon_Sig->SetEntries(18);
   sigZmumu_metNoMuon_Sig->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig->SetMarkerSize(0.8);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitle("MET_{sig}");
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_3 = new TH1F("h1_stack_3","h1",7,4,11);
   h1_stack_3->SetMinimum(0);
   h1_stack_3->SetMaximum(5.081611);
   h1_stack_3->SetDirectory(0);
   h1_stack_3->SetStats(0);
   h1_stack_3->SetLineStyle(0);
   h1_stack_3->SetMarkerStyle(20);
   h1_stack_3->GetXaxis()->SetNdivisions(505);
   h1_stack_3->GetXaxis()->SetLabelFont(42);
   h1_stack_3->GetXaxis()->SetLabelOffset(999);
   h1_stack_3->GetXaxis()->SetLabelSize(0);
   h1_stack_3->GetXaxis()->SetTitleSize(0.06);
   h1_stack_3->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_3->GetXaxis()->SetTitleFont(42);
   h1_stack_3->GetYaxis()->SetNdivisions(505);
   h1_stack_3->GetYaxis()->SetLabelFont(42);
   h1_stack_3->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetYaxis()->SetLabelSize(0.06);
   h1_stack_3->GetYaxis()->SetTitleSize(0.095);
   h1_stack_3->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_3->GetZaxis()->SetNdivisions(505);
   h1_stack_3->GetZaxis()->SetLabelFont(42);
   h1_stack_3->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetZaxis()->SetLabelSize(0.03);
   h1_stack_3->GetZaxis()->SetTitleSize(0.06);
   h1_stack_3->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_3);
   
   
   TH1D *sigZmumu_metNoMuon_Sig = new TH1D("sigZmumu_metNoMuon_Sig","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig->SetBinContent(1,0.05096845);
   sigZmumu_metNoMuon_Sig->SetBinContent(5,0.09060062);
   sigZmumu_metNoMuon_Sig->SetBinError(1,0.05096845);
   sigZmumu_metNoMuon_Sig->SetBinError(5,0.09060062);
   sigZmumu_metNoMuon_Sig->SetEntries(3);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#669966");
   sigZmumu_metNoMuon_Sig->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigZmumu_metNoMuon_Sig->SetLineColor(ci);
   sigZmumu_metNoMuon_Sig->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon_Sig,"");
   
   TH1D *sigZmumu_metNoMuon_Sig = new TH1D("sigZmumu_metNoMuon_Sig","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig->SetBinContent(1,0.7375869);
   sigZmumu_metNoMuon_Sig->SetBinContent(2,1.02337);
   sigZmumu_metNoMuon_Sig->SetBinContent(3,0.9596397);
   sigZmumu_metNoMuon_Sig->SetBinContent(4,0.9876041);
   sigZmumu_metNoMuon_Sig->SetBinContent(5,0.7773336);
   sigZmumu_metNoMuon_Sig->SetBinContent(6,0.4977167);
   sigZmumu_metNoMuon_Sig->SetBinContent(7,0.2053013);
   sigZmumu_metNoMuon_Sig->SetBinContent(8,0.2778867);
   sigZmumu_metNoMuon_Sig->SetBinError(1,0.06386213);
   sigZmumu_metNoMuon_Sig->SetBinError(2,0.08099414);
   sigZmumu_metNoMuon_Sig->SetBinError(3,0.07991554);
   sigZmumu_metNoMuon_Sig->SetBinError(4,0.08432146);
   sigZmumu_metNoMuon_Sig->SetBinError(5,0.07541053);
   sigZmumu_metNoMuon_Sig->SetBinError(6,0.06008633);
   sigZmumu_metNoMuon_Sig->SetBinError(7,0.03689058);
   sigZmumu_metNoMuon_Sig->SetBinError(8,0.04516501);
   sigZmumu_metNoMuon_Sig->SetEntries(1161);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_metNoMuon_Sig->SetFillColor(ci);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_metNoMuon_Sig->SetLineColor(ci);
   sigZmumu_metNoMuon_Sig->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon_Sig,"");
   
   TH1D *sigZmumu_metNoMuon_Sig = new TH1D("sigZmumu_metNoMuon_Sig","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig->SetBinContent(1,3.7883);
   sigZmumu_metNoMuon_Sig->SetBinContent(2,0.8690922);
   sigZmumu_metNoMuon_Sig->SetBinContent(3,3.522459);
   sigZmumu_metNoMuon_Sig->SetBinContent(4,2.035704);
   sigZmumu_metNoMuon_Sig->SetBinContent(5,1.042724);
   sigZmumu_metNoMuon_Sig->SetBinContent(6,0.6611303);
   sigZmumu_metNoMuon_Sig->SetBinContent(8,0.4741521);
   sigZmumu_metNoMuon_Sig->SetBinError(1,1.051329);
   sigZmumu_metNoMuon_Sig->SetBinError(2,0.5524769);
   sigZmumu_metNoMuon_Sig->SetBinError(3,1.123078);
   sigZmumu_metNoMuon_Sig->SetBinError(4,0.8295798);
   sigZmumu_metNoMuon_Sig->SetBinError(5,0.602737);
   sigZmumu_metNoMuon_Sig->SetBinError(6,0.4675323);
   sigZmumu_metNoMuon_Sig->SetBinError(8,0.4741521);
   sigZmumu_metNoMuon_Sig->SetEntries(75);

   ci = TColor::GetColor("#006699");
   sigZmumu_metNoMuon_Sig->SetFillColor(ci);

   ci = TColor::GetColor("#006699");
   sigZmumu_metNoMuon_Sig->SetLineColor(ci);
   sigZmumu_metNoMuon_Sig->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_metNoMuon_Sig,"");
   h1->Draw("histsame");
   
   TH1D *sigZmumu_metNoMuon_Sig = new TH1D("sigZmumu_metNoMuon_Sig","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig->SetBinContent(1,3);
   sigZmumu_metNoMuon_Sig->SetBinContent(2,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(3,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(4,6);
   sigZmumu_metNoMuon_Sig->SetBinContent(5,1);
   sigZmumu_metNoMuon_Sig->SetBinContent(6,1);
   sigZmumu_metNoMuon_Sig->SetBinContent(7,2);
   sigZmumu_metNoMuon_Sig->SetBinContent(8,1);
   sigZmumu_metNoMuon_Sig->SetBinError(1,1.732051);
   sigZmumu_metNoMuon_Sig->SetBinError(2,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(3,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(4,2.44949);
   sigZmumu_metNoMuon_Sig->SetBinError(5,1);
   sigZmumu_metNoMuon_Sig->SetBinError(6,1);
   sigZmumu_metNoMuon_Sig->SetBinError(7,1.414214);
   sigZmumu_metNoMuon_Sig->SetBinError(8,1);
   sigZmumu_metNoMuon_Sig->SetMinimum(0);
   sigZmumu_metNoMuon_Sig->SetMaximum(8.4);
   sigZmumu_metNoMuon_Sig->SetEntries(18);
   sigZmumu_metNoMuon_Sig->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig->SetMarkerSize(0.8);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitle("MET_{sig}");
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon_Sig->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig->Draw("P0E1same");
   
   TLegend *leg = new TLegend(0.55,0.7,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigZmumu_metNoMuon_Sig","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon_Sig","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon_Sig","Z#rightarrow#nu#nu EWK","F");

   ci = TColor::GetColor("#0066cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0066cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_metNoMuon_Sig","Z#rightarrow#nu#nu QCD","F");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006699");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigZmumu_metNoMuon_Sig__3 = new TH1D("sigZmumu_metNoMuon_Sig__3","metNoMuon_Sig",7,4,11);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(1,3);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(2,2);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(3,2);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(4,6);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(5,1);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(6,1);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(7,2);
   sigZmumu_metNoMuon_Sig__3->SetBinContent(8,1);
   sigZmumu_metNoMuon_Sig__3->SetBinError(1,1.732051);
   sigZmumu_metNoMuon_Sig__3->SetBinError(2,1.414214);
   sigZmumu_metNoMuon_Sig__3->SetBinError(3,1.414214);
   sigZmumu_metNoMuon_Sig__3->SetBinError(4,2.44949);
   sigZmumu_metNoMuon_Sig__3->SetBinError(5,1);
   sigZmumu_metNoMuon_Sig__3->SetBinError(6,1);
   sigZmumu_metNoMuon_Sig__3->SetBinError(7,1.414214);
   sigZmumu_metNoMuon_Sig__3->SetBinError(8,1);
   sigZmumu_metNoMuon_Sig__3->SetMinimum(0);
   sigZmumu_metNoMuon_Sig__3->SetMaximum(8.4);
   sigZmumu_metNoMuon_Sig__3->SetEntries(18);
   sigZmumu_metNoMuon_Sig__3->SetDirectory(0);
   sigZmumu_metNoMuon_Sig__3->SetLineStyle(0);
   sigZmumu_metNoMuon_Sig__3->SetMarkerStyle(20);
   sigZmumu_metNoMuon_Sig__3->SetMarkerSize(0.8);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetTitle("MET_{sig}");
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetLabelOffset(999);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetLabelSize(0);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_metNoMuon_Sig__3->GetXaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetTitle("Events");
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_metNoMuon_Sig__3->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_metNoMuon_Sig__3->GetZaxis()->SetLabelFont(42);
   sigZmumu_metNoMuon_Sig__3->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_metNoMuon_Sig__3->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_metNoMuon_Sig__3->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_metNoMuon_Sig__3->GetZaxis()->SetTitleFont(42);
   sigZmumu_metNoMuon_Sig__3->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(2,-1.914893,12,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",7,4,11);
   h1_num->SetBinContent(1,0.6554718);
   h1_num->SetBinContent(2,1.056824);
   h1_num->SetBinContent(3,0.4462196);
   h1_num->SetBinContent(4,1.984581);
   h1_num->SetBinContent(5,0.5233799);
   h1_num->SetBinContent(6,0.8629267);
   h1_num->SetBinContent(7,9.741782);
   h1_num->SetBinContent(8,1.329719);
   h1_num->SetBinError(1,0.4074571);
   h1_num->SetBinError(2,0.8097357);
   h1_num->SetBinError(3,0.334844);
   h1_num->SetBinError(4,0.9777705);
   h1_num->SetBinError(5,0.5497536);
   h1_num->SetBinError(6,0.9315841);
   h1_num->SetBinError(7,7.107419);
   h1_num->SetBinError(8,1.573975);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(4.352919);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("MET_{sig}");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(4,1,11,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
