{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 09:06:36 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(925.7143,-0.3478893,2297.143,11.24842);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigZmumu_Dijet_Mjj = new TH1D("sigZmumu_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj->SetBinContent(1,6);
   sigZmumu_Dijet_Mjj->SetBinContent(2,2);
   sigZmumu_Dijet_Mjj->SetBinContent(3,5);
   sigZmumu_Dijet_Mjj->SetBinContent(4,1);
   sigZmumu_Dijet_Mjj->SetBinContent(5,1);
   sigZmumu_Dijet_Mjj->SetBinContent(7,3);
   sigZmumu_Dijet_Mjj->SetBinError(1,2.44949);
   sigZmumu_Dijet_Mjj->SetBinError(2,1.414214);
   sigZmumu_Dijet_Mjj->SetBinError(3,2.236068);
   sigZmumu_Dijet_Mjj->SetBinError(4,1);
   sigZmumu_Dijet_Mjj->SetBinError(5,1);
   sigZmumu_Dijet_Mjj->SetBinError(7,1.732051);
   sigZmumu_Dijet_Mjj->SetMinimum(0);
   sigZmumu_Dijet_Mjj->SetMaximum(10.08879);
   sigZmumu_Dijet_Mjj->SetEntries(18);
   sigZmumu_Dijet_Mjj->SetLineStyle(0);
   sigZmumu_Dijet_Mjj->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj->SetMarkerSize(0.8);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_2 = new TH1F("h1_stack_2","h1",6,1200,2160);
   h1_stack_2->SetMinimum(0);
   h1_stack_2->SetMaximum(9.224686);
   h1_stack_2->SetDirectory(0);
   h1_stack_2->SetStats(0);
   h1_stack_2->SetLineStyle(0);
   h1_stack_2->SetMarkerStyle(20);
   h1_stack_2->GetXaxis()->SetNdivisions(505);
   h1_stack_2->GetXaxis()->SetLabelFont(42);
   h1_stack_2->GetXaxis()->SetLabelOffset(999);
   h1_stack_2->GetXaxis()->SetLabelSize(0);
   h1_stack_2->GetXaxis()->SetTitleSize(0.06);
   h1_stack_2->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_2->GetXaxis()->SetTitleFont(42);
   h1_stack_2->GetYaxis()->SetNdivisions(505);
   h1_stack_2->GetYaxis()->SetLabelFont(42);
   h1_stack_2->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_2->GetYaxis()->SetLabelSize(0.06);
   h1_stack_2->GetYaxis()->SetTitleSize(0.095);
   h1_stack_2->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_2->GetZaxis()->SetNdivisions(505);
   h1_stack_2->GetZaxis()->SetLabelFont(42);
   h1_stack_2->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_2->GetZaxis()->SetLabelSize(0.03);
   h1_stack_2->GetZaxis()->SetTitleSize(0.06);
   h1_stack_2->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_2);
   
   
   TH1D *sigZmumu_Dijet_Mjj = new TH1D("sigZmumu_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj->SetBinContent(1,0.1415691);
   sigZmumu_Dijet_Mjj->SetBinError(1,0.1039531);
   sigZmumu_Dijet_Mjj->SetEntries(3);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#669966");
   sigZmumu_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigZmumu_Dijet_Mjj->SetLineColor(ci);
   sigZmumu_Dijet_Mjj->SetLineStyle(0);
   sigZmumu_Dijet_Mjj->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_Mjj,"");
   
   TH1D *sigZmumu_Dijet_Mjj = new TH1D("sigZmumu_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj->SetBinContent(1,1.437567);
   sigZmumu_Dijet_Mjj->SetBinContent(2,1.284088);
   sigZmumu_Dijet_Mjj->SetBinContent(3,0.7883936);
   sigZmumu_Dijet_Mjj->SetBinContent(4,0.6269889);
   sigZmumu_Dijet_Mjj->SetBinContent(5,0.4406838);
   sigZmumu_Dijet_Mjj->SetBinContent(6,0.2759939);
   sigZmumu_Dijet_Mjj->SetBinContent(7,0.6127243);
   sigZmumu_Dijet_Mjj->SetBinError(1,0.09832331);
   sigZmumu_Dijet_Mjj->SetBinError(2,0.09213906);
   sigZmumu_Dijet_Mjj->SetBinError(3,0.072884);
   sigZmumu_Dijet_Mjj->SetBinError(4,0.06537258);
   sigZmumu_Dijet_Mjj->SetBinError(5,0.05378934);
   sigZmumu_Dijet_Mjj->SetBinError(6,0.0433672);
   sigZmumu_Dijet_Mjj->SetBinError(7,0.06569775);
   sigZmumu_Dijet_Mjj->SetEntries(1161);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_Dijet_Mjj->SetLineColor(ci);
   sigZmumu_Dijet_Mjj->SetLineStyle(0);
   sigZmumu_Dijet_Mjj->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_Mjj,"");
   
   TH1D *sigZmumu_Dijet_Mjj = new TH1D("sigZmumu_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj->SetBinContent(1,7.206279);
   sigZmumu_Dijet_Mjj->SetBinContent(2,1.784398);
   sigZmumu_Dijet_Mjj->SetBinContent(3,1.602737);
   sigZmumu_Dijet_Mjj->SetBinContent(4,0.8729005);
   sigZmumu_Dijet_Mjj->SetBinContent(5,0.8335765);
   sigZmumu_Dijet_Mjj->SetBinContent(6,0.09367001);
   sigZmumu_Dijet_Mjj->SetBinError(1,1.574335);
   sigZmumu_Dijet_Mjj->SetBinError(2,0.7256618);
   sigZmumu_Dijet_Mjj->SetBinError(3,0.7331774);
   sigZmumu_Dijet_Mjj->SetBinError(4,0.5992368);
   sigZmumu_Dijet_Mjj->SetBinError(5,0.5061666);
   sigZmumu_Dijet_Mjj->SetBinError(6,0.09367001);
   sigZmumu_Dijet_Mjj->SetEntries(75);

   ci = TColor::GetColor("#006699");
   sigZmumu_Dijet_Mjj->SetFillColor(ci);

   ci = TColor::GetColor("#006699");
   sigZmumu_Dijet_Mjj->SetLineColor(ci);
   sigZmumu_Dijet_Mjj->SetLineStyle(0);
   sigZmumu_Dijet_Mjj->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_Mjj,"");
   h1->Draw("histsame");
   
   TH1D *sigZmumu_Dijet_Mjj = new TH1D("sigZmumu_Dijet_Mjj","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj->SetBinContent(1,6);
   sigZmumu_Dijet_Mjj->SetBinContent(2,2);
   sigZmumu_Dijet_Mjj->SetBinContent(3,5);
   sigZmumu_Dijet_Mjj->SetBinContent(4,1);
   sigZmumu_Dijet_Mjj->SetBinContent(5,1);
   sigZmumu_Dijet_Mjj->SetBinContent(7,3);
   sigZmumu_Dijet_Mjj->SetBinError(1,2.44949);
   sigZmumu_Dijet_Mjj->SetBinError(2,1.414214);
   sigZmumu_Dijet_Mjj->SetBinError(3,2.236068);
   sigZmumu_Dijet_Mjj->SetBinError(4,1);
   sigZmumu_Dijet_Mjj->SetBinError(5,1);
   sigZmumu_Dijet_Mjj->SetBinError(7,1.732051);
   sigZmumu_Dijet_Mjj->SetMinimum(0);
   sigZmumu_Dijet_Mjj->SetMaximum(10.08879);
   sigZmumu_Dijet_Mjj->SetEntries(18);
   sigZmumu_Dijet_Mjj->SetLineStyle(0);
   sigZmumu_Dijet_Mjj->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj->SetMarkerSize(0.8);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_Mjj->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj->Draw("P0E1same");
   
   TLegend *leg = new TLegend(0.55,0.7,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigZmumu_Dijet_Mjj","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_Mjj","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_Mjj","Z#rightarrow#nu#nu EWK","F");

   ci = TColor::GetColor("#0066cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0066cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_Mjj","Z#rightarrow#nu#nu QCD","F");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006699");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigZmumu_Dijet_Mjj__2 = new TH1D("sigZmumu_Dijet_Mjj__2","Dijet_Mjj",6,1200,2160);
   sigZmumu_Dijet_Mjj__2->SetBinContent(1,6);
   sigZmumu_Dijet_Mjj__2->SetBinContent(2,2);
   sigZmumu_Dijet_Mjj__2->SetBinContent(3,5);
   sigZmumu_Dijet_Mjj__2->SetBinContent(4,1);
   sigZmumu_Dijet_Mjj__2->SetBinContent(5,1);
   sigZmumu_Dijet_Mjj__2->SetBinContent(7,3);
   sigZmumu_Dijet_Mjj__2->SetBinError(1,2.44949);
   sigZmumu_Dijet_Mjj__2->SetBinError(2,1.414214);
   sigZmumu_Dijet_Mjj__2->SetBinError(3,2.236068);
   sigZmumu_Dijet_Mjj__2->SetBinError(4,1);
   sigZmumu_Dijet_Mjj__2->SetBinError(5,1);
   sigZmumu_Dijet_Mjj__2->SetBinError(7,1.732051);
   sigZmumu_Dijet_Mjj__2->SetMinimum(0);
   sigZmumu_Dijet_Mjj__2->SetMaximum(10.08879);
   sigZmumu_Dijet_Mjj__2->SetEntries(18);
   sigZmumu_Dijet_Mjj__2->SetDirectory(0);
   sigZmumu_Dijet_Mjj__2->SetLineStyle(0);
   sigZmumu_Dijet_Mjj__2->SetMarkerStyle(20);
   sigZmumu_Dijet_Mjj__2->SetMarkerSize(0.8);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetTitle("M_{jj} [GeV]");
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_Mjj__2->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_Mjj__2->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_Mjj__2->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_Mjj__2->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_Mjj__2->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_Mjj__2->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_Mjj__2->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_Mjj__2->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(925.7143,-1.914893,2297.143,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",6,1200,2160);
   h1_num->SetBinContent(1,0.6829501);
   h1_num->SetBinContent(2,0.6517873);
   h1_num->SetBinContent(3,2.091061);
   h1_num->SetBinContent(4,0.6667159);
   h1_num->SetBinContent(5,0.784769);
   h1_num->SetBinContent(7,4.896166);
   h1_num->SetBinError(1,0.3046938);
   h1_num->SetBinError(2,0.4863698);
   h1_num->SetBinError(3,1.135635);
   h1_num->SetBinError(4,0.7185442);
   h1_num->SetBinError(5,0.8450649);
   h1_num->SetBinError(7,2.875138);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(8.348089);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("M_{jj} [GeV]");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(1200,1,2160,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
