{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 09:06:36 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(2.514286,-0.2413793,7.942857,7.804598);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigZmumu_Dijet_DeltaEta = new TH1D("sigZmumu_Dijet_DeltaEta","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(2,3);
   sigZmumu_Dijet_DeltaEta->SetBinContent(3,1);
   sigZmumu_Dijet_DeltaEta->SetBinContent(4,4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(5,3);
   sigZmumu_Dijet_DeltaEta->SetBinContent(6,5);
   sigZmumu_Dijet_DeltaEta->SetBinContent(7,2);
   sigZmumu_Dijet_DeltaEta->SetBinError(2,1.732051);
   sigZmumu_Dijet_DeltaEta->SetBinError(3,1);
   sigZmumu_Dijet_DeltaEta->SetBinError(4,2);
   sigZmumu_Dijet_DeltaEta->SetBinError(5,1.732051);
   sigZmumu_Dijet_DeltaEta->SetBinError(6,2.236068);
   sigZmumu_Dijet_DeltaEta->SetBinError(7,1.414214);
   sigZmumu_Dijet_DeltaEta->SetMinimum(0);
   sigZmumu_Dijet_DeltaEta->SetMaximum(7);
   sigZmumu_Dijet_DeltaEta->SetEntries(18);
   sigZmumu_Dijet_DeltaEta->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta->SetMarkerSize(0.8);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitle("#Delta#eta_{jj}");
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_1 = new TH1F("h1_stack_1","h1",10,3.6,7.4);
   h1_stack_1->SetMinimum(0);
   h1_stack_1->SetMaximum(4.459912);
   h1_stack_1->SetDirectory(0);
   h1_stack_1->SetStats(0);
   h1_stack_1->SetLineStyle(0);
   h1_stack_1->SetMarkerStyle(20);
   h1_stack_1->GetXaxis()->SetNdivisions(505);
   h1_stack_1->GetXaxis()->SetLabelFont(42);
   h1_stack_1->GetXaxis()->SetLabelOffset(999);
   h1_stack_1->GetXaxis()->SetLabelSize(0);
   h1_stack_1->GetXaxis()->SetTitleSize(0.06);
   h1_stack_1->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_1->GetXaxis()->SetTitleFont(42);
   h1_stack_1->GetYaxis()->SetNdivisions(505);
   h1_stack_1->GetYaxis()->SetLabelFont(42);
   h1_stack_1->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_1->GetYaxis()->SetLabelSize(0.06);
   h1_stack_1->GetYaxis()->SetTitleSize(0.095);
   h1_stack_1->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_1->GetZaxis()->SetNdivisions(505);
   h1_stack_1->GetZaxis()->SetLabelFont(42);
   h1_stack_1->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_1->GetZaxis()->SetLabelSize(0.03);
   h1_stack_1->GetZaxis()->SetTitleSize(0.06);
   h1_stack_1->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_1);
   
   
   TH1D *sigZmumu_Dijet_DeltaEta = new TH1D("sigZmumu_Dijet_DeltaEta","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(4,0.09060062);
   sigZmumu_Dijet_DeltaEta->SetBinContent(7,0.05096845);
   sigZmumu_Dijet_DeltaEta->SetBinError(4,0.09060062);
   sigZmumu_Dijet_DeltaEta->SetBinError(7,0.05096845);
   sigZmumu_Dijet_DeltaEta->SetEntries(3);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#669966");
   sigZmumu_Dijet_DeltaEta->SetFillColor(ci);

   ci = TColor::GetColor("#669966");
   sigZmumu_Dijet_DeltaEta->SetLineColor(ci);
   sigZmumu_Dijet_DeltaEta->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_DeltaEta,"");
   
   TH1D *sigZmumu_Dijet_DeltaEta = new TH1D("sigZmumu_Dijet_DeltaEta","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(1,0.2742721);
   sigZmumu_Dijet_DeltaEta->SetBinContent(2,0.4874502);
   sigZmumu_Dijet_DeltaEta->SetBinContent(3,0.8223183);
   sigZmumu_Dijet_DeltaEta->SetBinContent(4,1.056142);
   sigZmumu_Dijet_DeltaEta->SetBinContent(5,1.166823);
   sigZmumu_Dijet_DeltaEta->SetBinContent(6,0.8444899);
   sigZmumu_Dijet_DeltaEta->SetBinContent(7,0.4358595);
   sigZmumu_Dijet_DeltaEta->SetBinContent(8,0.2733946);
   sigZmumu_Dijet_DeltaEta->SetBinContent(9,0.06610068);
   sigZmumu_Dijet_DeltaEta->SetBinContent(10,0.01986591);
   sigZmumu_Dijet_DeltaEta->SetBinContent(11,0.01972299);
   sigZmumu_Dijet_DeltaEta->SetBinError(1,0.04305126);
   sigZmumu_Dijet_DeltaEta->SetBinError(2,0.05735329);
   sigZmumu_Dijet_DeltaEta->SetBinError(3,0.07527089);
   sigZmumu_Dijet_DeltaEta->SetBinError(4,0.08647817);
   sigZmumu_Dijet_DeltaEta->SetBinError(5,0.08905198);
   sigZmumu_Dijet_DeltaEta->SetBinError(6,0.07483169);
   sigZmumu_Dijet_DeltaEta->SetBinError(7,0.0526433);
   sigZmumu_Dijet_DeltaEta->SetBinError(8,0.04106078);
   sigZmumu_Dijet_DeltaEta->SetBinError(9,0.01925483);
   sigZmumu_Dijet_DeltaEta->SetBinError(10,0.009250104);
   sigZmumu_Dijet_DeltaEta->SetBinError(11,0.01011358);
   sigZmumu_Dijet_DeltaEta->SetEntries(1161);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_Dijet_DeltaEta->SetFillColor(ci);

   ci = TColor::GetColor("#0066cc");
   sigZmumu_Dijet_DeltaEta->SetLineColor(ci);
   sigZmumu_Dijet_DeltaEta->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_DeltaEta,"");
   
   TH1D *sigZmumu_Dijet_DeltaEta = new TH1D("sigZmumu_Dijet_DeltaEta","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(2,0.6671034);
   sigZmumu_Dijet_DeltaEta->SetBinContent(3,1.867823);
   sigZmumu_Dijet_DeltaEta->SetBinContent(4,3.100792);
   sigZmumu_Dijet_DeltaEta->SetBinContent(5,1.900759);
   sigZmumu_Dijet_DeltaEta->SetBinContent(6,2.941689);
   sigZmumu_Dijet_DeltaEta->SetBinContent(7,1.3047);
   sigZmumu_Dijet_DeltaEta->SetBinContent(8,0.5170243);
   sigZmumu_Dijet_DeltaEta->SetBinContent(11,0.09367001);
   sigZmumu_Dijet_DeltaEta->SetBinError(2,0.4718309);
   sigZmumu_Dijet_DeltaEta->SetBinError(3,0.8433538);
   sigZmumu_Dijet_DeltaEta->SetBinError(4,1.034212);
   sigZmumu_Dijet_DeltaEta->SetBinError(5,0.8039513);
   sigZmumu_Dijet_DeltaEta->SetBinError(6,0.9907631);
   sigZmumu_Dijet_DeltaEta->SetBinError(7,0.6601352);
   sigZmumu_Dijet_DeltaEta->SetBinError(8,0.301264);
   sigZmumu_Dijet_DeltaEta->SetBinError(11,0.09367001);
   sigZmumu_Dijet_DeltaEta->SetEntries(75);

   ci = TColor::GetColor("#006699");
   sigZmumu_Dijet_DeltaEta->SetFillColor(ci);

   ci = TColor::GetColor("#006699");
   sigZmumu_Dijet_DeltaEta->SetLineColor(ci);
   sigZmumu_Dijet_DeltaEta->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleOffset(1.25);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleFont(42);
   h1->Add(sigZmumu_Dijet_DeltaEta,"");
   h1->Draw("histsame");
   
   TH1D *sigZmumu_Dijet_DeltaEta = new TH1D("sigZmumu_Dijet_DeltaEta","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(2,3);
   sigZmumu_Dijet_DeltaEta->SetBinContent(3,1);
   sigZmumu_Dijet_DeltaEta->SetBinContent(4,4);
   sigZmumu_Dijet_DeltaEta->SetBinContent(5,3);
   sigZmumu_Dijet_DeltaEta->SetBinContent(6,5);
   sigZmumu_Dijet_DeltaEta->SetBinContent(7,2);
   sigZmumu_Dijet_DeltaEta->SetBinError(2,1.732051);
   sigZmumu_Dijet_DeltaEta->SetBinError(3,1);
   sigZmumu_Dijet_DeltaEta->SetBinError(4,2);
   sigZmumu_Dijet_DeltaEta->SetBinError(5,1.732051);
   sigZmumu_Dijet_DeltaEta->SetBinError(6,2.236068);
   sigZmumu_Dijet_DeltaEta->SetBinError(7,1.414214);
   sigZmumu_Dijet_DeltaEta->SetMinimum(0);
   sigZmumu_Dijet_DeltaEta->SetMaximum(7);
   sigZmumu_Dijet_DeltaEta->SetEntries(18);
   sigZmumu_Dijet_DeltaEta->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta->SetMarkerSize(0.8);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitle("#Delta#eta_{jj}");
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_DeltaEta->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta->Draw("P0E1same");
   
   TLegend *leg = new TLegend(0.55,0.7,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigZmumu_Dijet_DeltaEta","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_DeltaEta","VV","F");

   ci = TColor::GetColor("#669966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#669966");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_DeltaEta","Z#rightarrow#nu#nu EWK","F");

   ci = TColor::GetColor("#0066cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0066cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigZmumu_Dijet_DeltaEta","Z#rightarrow#nu#nu QCD","F");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006699");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigZmumu_Dijet_DeltaEta__1 = new TH1D("sigZmumu_Dijet_DeltaEta__1","Dijet_DeltaEta",10,3.6,7.4);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(2,3);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(3,1);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(4,4);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(5,3);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(6,5);
   sigZmumu_Dijet_DeltaEta__1->SetBinContent(7,2);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(2,1.732051);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(3,1);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(4,2);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(5,1.732051);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(6,2.236068);
   sigZmumu_Dijet_DeltaEta__1->SetBinError(7,1.414214);
   sigZmumu_Dijet_DeltaEta__1->SetMinimum(0);
   sigZmumu_Dijet_DeltaEta__1->SetMaximum(7);
   sigZmumu_Dijet_DeltaEta__1->SetEntries(18);
   sigZmumu_Dijet_DeltaEta__1->SetDirectory(0);
   sigZmumu_Dijet_DeltaEta__1->SetLineStyle(0);
   sigZmumu_Dijet_DeltaEta__1->SetMarkerStyle(20);
   sigZmumu_Dijet_DeltaEta__1->SetMarkerSize(0.8);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetTitle("#Delta#eta_{jj}");
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetLabelOffset(999);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetLabelSize(0);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetTitleOffset(0.9);
   sigZmumu_Dijet_DeltaEta__1->GetXaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetTitle("Events");
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetLabelSize(0.06);
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetTitleSize(0.095);
   sigZmumu_Dijet_DeltaEta__1->GetYaxis()->SetTitleOffset(0.85);
   sigZmumu_Dijet_DeltaEta__1->GetZaxis()->SetLabelFont(42);
   sigZmumu_Dijet_DeltaEta__1->GetZaxis()->SetLabelOffset(0.007);
   sigZmumu_Dijet_DeltaEta__1->GetZaxis()->SetLabelSize(0.05);
   sigZmumu_Dijet_DeltaEta__1->GetZaxis()->SetTitleSize(0.06);
   sigZmumu_Dijet_DeltaEta__1->GetZaxis()->SetTitleFont(42);
   sigZmumu_Dijet_DeltaEta__1->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(2.514286,-1.914893,7.942857,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",10,3.6,7.4);
   h1_num->SetBinContent(2,2.598407);
   h1_num->SetBinContent(3,0.3717277);
   h1_num->SetBinContent(4,0.9417226);
   h1_num->SetBinContent(5,0.9779689);
   h1_num->SetBinContent(6,1.320593);
   h1_num->SetBinContent(7,1.116366);
   h1_num->SetBinError(2,1.84251);
   h1_num->SetBinError(3,0.3897054);
   h1_num->SetBinError(4,0.5244597);
   h1_num->SetBinError(5,0.6207306);
   h1_num->SetBinError(6,0.6847582);
   h1_num->SetBinError(7,0.8913096);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(9.813125);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("#Delta#eta_{jj}");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(3.6,1,7.4,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
