{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Dec 30 14:18:57 2015) by ROOT version5.34/11
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.3,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(2.059545,-0.337931,3.26182,10.92644);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(2);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.2);
   upper->SetBottomMargin(0.03);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   upper->SetFrameFillStyle(0);
   upper->SetFrameBorderMode(0);
   
   TH1D *sigWel_MinDeltaPhiMetAllJets = new TH1D("sigWel_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(1,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(2,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(3,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(4,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(5,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(6,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(7,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(8,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(9,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(10,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(11,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(12,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(13,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(14,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(15,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(17,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(18,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(19,7);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(20,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(21,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(1,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(2,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(3,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(4,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(5,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(6,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(7,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(8,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(9,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(10,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(11,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(12,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(13,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(14,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(15,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(17,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(18,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(19,2.645751);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(20,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(21,1);
   sigWel_MinDeltaPhiMetAllJets->SetMinimum(0);
   sigWel_MinDeltaPhiMetAllJets->SetMaximum(9.8);
   sigWel_MinDeltaPhiMetAllJets->SetEntries(68);
   sigWel_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerSize(0.8);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(999);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitle("Events");
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.095);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(0.85);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->Draw("P0E1");
   
   THStack *h1 = new THStack();
   h1->SetName("h1");
   h1->SetTitle("h1");
   
   TH1F *h1_stack_3 = new TH1F("h1_stack_3","h1",22,2.3,3.141593);
   h1_stack_3->SetMinimum(0);
   h1_stack_3->SetMaximum(6.8907);
   h1_stack_3->SetDirectory(0);
   h1_stack_3->SetStats(0);
   h1_stack_3->SetLineStyle(0);
   h1_stack_3->SetMarkerStyle(20);
   h1_stack_3->GetXaxis()->SetNdivisions(505);
   h1_stack_3->GetXaxis()->SetLabelFont(42);
   h1_stack_3->GetXaxis()->SetLabelOffset(999);
   h1_stack_3->GetXaxis()->SetLabelSize(0);
   h1_stack_3->GetXaxis()->SetTitleSize(0.06);
   h1_stack_3->GetXaxis()->SetTitleOffset(0.9);
   h1_stack_3->GetXaxis()->SetTitleFont(42);
   h1_stack_3->GetYaxis()->SetNdivisions(505);
   h1_stack_3->GetYaxis()->SetLabelFont(42);
   h1_stack_3->GetYaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetYaxis()->SetLabelSize(0.06);
   h1_stack_3->GetYaxis()->SetTitleSize(0.095);
   h1_stack_3->GetYaxis()->SetTitleOffset(0.85);
   h1_stack_3->GetZaxis()->SetNdivisions(505);
   h1_stack_3->GetZaxis()->SetLabelFont(42);
   h1_stack_3->GetZaxis()->SetLabelOffset(0.007);
   h1_stack_3->GetZaxis()->SetLabelSize(0.03);
   h1_stack_3->GetZaxis()->SetTitleSize(0.06);
   h1_stack_3->GetZaxis()->SetTitleFont(42);
   h1->SetHistogram(h1_stack_3);
   
   
   TH1D *sigWel_MinDeltaPhiMetAllJets = new TH1D("sigWel_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(2,0.5813969);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(3,0.7912462);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(7,0.3593992);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(11,0.5985348);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(13,0.2709879);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(16,0.2608767);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(18,0.2855943);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(2,0.5813969);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(3,0.6003995);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(7,0.3593992);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(11,0.5985348);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(13,0.2709879);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(16,0.2001953);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(18,0.2855943);
   sigWel_MinDeltaPhiMetAllJets->SetEntries(9);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#9999cc");
   sigWel_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#9999cc");
   sigWel_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWel_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWel_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWel_MinDeltaPhiMetAllJets = new TH1D("sigWel_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(1,2.462158);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(2,3.563807);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(3,5.05182);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(4,2.348926);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(5,2.707561);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(6,4.618241);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(7,3.791719);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(8,2.719046);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(9,3.190865);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(10,5.048625);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(11,4.508031);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(12,4.809275);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(13,4.288828);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(14,4.692832);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(15,2.884856);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(16,1.356463);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(17,1.043801);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(18,2.093416);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(19,0.1455911);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(20,0.1541692);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(21,0.05802951);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(22,0.0619426);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(1,0.9585878);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(2,1.312502);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(3,1.49789);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(4,0.9319255);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(5,0.8753042);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(6,1.756213);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(7,1.304958);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(8,1.056973);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(9,1.222904);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(10,1.513947);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(11,1.567445);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(12,1.608159);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(13,1.486642);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(14,1.60955);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(15,1.129697);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(16,0.6628279);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(17,0.6833411);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(18,1.083726);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(19,0.03725556);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(20,0.03825493);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(21,0.02271889);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(22,0.02439363);
   sigWel_MinDeltaPhiMetAllJets->SetEntries(3653);

   ci = TColor::GetColor("#cc6600");
   sigWel_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#cc6600");
   sigWel_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWel_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWel_MinDeltaPhiMetAllJets,"");
   
   TH1D *sigWel_MinDeltaPhiMetAllJets = new TH1D("sigWel_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(1,0.174914);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(4,0.01181176);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(7,0.01446084);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(8,0.02493721);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(19,0.483737);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(1,0.174914);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(4,0.01181176);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(7,0.01446084);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(8,0.01763347);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(19,0.483737);
   sigWel_MinDeltaPhiMetAllJets->SetEntries(18);

   ci = TColor::GetColor("#993300");
   sigWel_MinDeltaPhiMetAllJets->SetFillColor(ci);

   ci = TColor::GetColor("#993300");
   sigWel_MinDeltaPhiMetAllJets->SetLineColor(ci);
   sigWel_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(1.25);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   h1->Add(sigWel_MinDeltaPhiMetAllJets,"");
   h1->Draw("histsame");
   
   TH1D *sigWel_MinDeltaPhiMetAllJets = new TH1D("sigWel_MinDeltaPhiMetAllJets","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(1,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(2,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(3,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(4,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(5,4);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(6,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(7,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(8,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(9,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(10,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(11,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(12,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(13,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(14,5);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(15,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(17,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(18,3);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(19,7);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(20,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinContent(21,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(1,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(2,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(3,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(4,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(5,2);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(6,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(7,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(8,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(9,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(10,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(11,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(12,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(13,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(14,2.236068);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(15,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(17,1.414214);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(18,1.732051);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(19,2.645751);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(20,1);
   sigWel_MinDeltaPhiMetAllJets->SetBinError(21,1);
   sigWel_MinDeltaPhiMetAllJets->SetMinimum(0);
   sigWel_MinDeltaPhiMetAllJets->SetMaximum(9.8);
   sigWel_MinDeltaPhiMetAllJets->SetEntries(68);
   sigWel_MinDeltaPhiMetAllJets->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets->SetMarkerSize(0.8);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelOffset(999);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetLabelSize(0);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitle("Events");
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetLabelSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleSize(0.095);
   sigWel_MinDeltaPhiMetAllJets->GetYaxis()->SetTitleOffset(0.85);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets->GetZaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets->Draw("P0E1same");
   
   TLegend *leg = new TLegend(0.7,0.55,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(10);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("sigWel_MinDeltaPhiMetAllJets","Data","LPE");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWel_MinDeltaPhiMetAllJets","Top","F");

   ci = TColor::GetColor("#9999cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#9999cc");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWel_MinDeltaPhiMetAllJets","W#rightarrow e#nu","F");

   ci = TColor::GetColor("#cc6600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cc6600");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("sigWel_MinDeltaPhiMetAllJets","W#rightarrow#tau#nu","F");

   ci = TColor::GetColor("#993300");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#993300");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1D *sigWel_MinDeltaPhiMetAllJets__3 = new TH1D("sigWel_MinDeltaPhiMetAllJets__3","MinDeltaPhiMetAllJets",22,2.3,3.141593);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(1,4);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(2,4);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(3,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(4,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(5,4);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(6,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(7,3);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(8,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(9,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(10,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(11,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(12,3);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(13,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(14,5);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(15,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(17,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(18,3);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(19,7);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(20,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinContent(21,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(1,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(2,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(3,1.414214);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(4,1.414214);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(5,2);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(6,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(7,1.732051);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(8,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(9,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(10,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(11,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(12,1.732051);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(13,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(14,2.236068);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(15,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(17,1.414214);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(18,1.732051);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(19,2.645751);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(20,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetBinError(21,1);
   sigWel_MinDeltaPhiMetAllJets__3->SetMinimum(0);
   sigWel_MinDeltaPhiMetAllJets__3->SetMaximum(9.8);
   sigWel_MinDeltaPhiMetAllJets__3->SetEntries(68);
   sigWel_MinDeltaPhiMetAllJets__3->SetDirectory(0);
   sigWel_MinDeltaPhiMetAllJets__3->SetLineStyle(0);
   sigWel_MinDeltaPhiMetAllJets__3->SetMarkerStyle(20);
   sigWel_MinDeltaPhiMetAllJets__3->SetMarkerSize(0.8);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelOffset(999);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetLabelSize(0);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleOffset(0.9);
   sigWel_MinDeltaPhiMetAllJets__3->GetXaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitle("Events");
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetLabelSize(0.06);
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitleSize(0.095);
   sigWel_MinDeltaPhiMetAllJets__3->GetYaxis()->SetTitleOffset(0.85);
   sigWel_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelFont(42);
   sigWel_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelOffset(0.007);
   sigWel_MinDeltaPhiMetAllJets__3->GetZaxis()->SetLabelSize(0.05);
   sigWel_MinDeltaPhiMetAllJets__3->GetZaxis()->SetTitleSize(0.06);
   sigWel_MinDeltaPhiMetAllJets__3->GetZaxis()->SetTitleFont(42);
   sigWel_MinDeltaPhiMetAllJets__3->Draw("sameaxis");
   upper->Modified();
   c1->cd();
  
// ------------>Primitives in pad: lower
   lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(2.059545,-1.914893,3.26182,2.340426);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(2);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.2);
   lower->SetTopMargin(0.08);
   lower->SetBottomMargin(0.45);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   lower->SetFrameFillStyle(0);
   lower->SetFrameBorderMode(0);
   
   TH1D *h1_num = new TH1D("h1_num","",22,2.3,3.141593);
   h1_num->SetBinContent(1,1.516834);
   h1_num->SetBinContent(2,0.9649707);
   h1_num->SetBinContent(3,0.3422861);
   h1_num->SetBinContent(4,0.8471929);
   h1_num->SetBinContent(5,1.477344);
   h1_num->SetBinContent(6,1.082663);
   h1_num->SetBinContent(7,0.720188);
   h1_num->SetBinContent(8,1.822168);
   h1_num->SetBinContent(9,0.3133946);
   h1_num->SetBinContent(10,0.9903688);
   h1_num->SetBinContent(11,0.9791316);
   h1_num->SetBinContent(12,0.6237947);
   h1_num->SetBinContent(13,1.096536);
   h1_num->SetBinContent(14,1.065455);
   h1_num->SetBinContent(15,0.3466378);
   h1_num->SetBinContent(17,1.916074);
   h1_num->SetBinContent(18,1.261029);
   h1_num->SetBinContent(19,11.12297);
   h1_num->SetBinContent(20,6.486378);
   h1_num->SetBinContent(21,17.23261);
   h1_num->SetBinError(1,0.943045);
   h1_num->SetBinError(2,0.5869115);
   h1_num->SetBinError(3,0.259839);
   h1_num->SetBinError(4,0.6861011);
   h1_num->SetBinError(5,0.8796227);
   h1_num->SetBinError(6,0.635562);
   h1_num->SetBinError(7,0.4771367);
   h1_num->SetBinError(8,1.07557);
   h1_num->SetBinError(9,0.3356224);
   h1_num->SetBinError(10,0.53326);
   h1_num->SetBinError(11,0.5433558);
   h1_num->SetBinError(12,0.4161921);
   h1_num->SetBinError(13,0.610356);
   h1_num->SetBinError(14,0.6004815);
   h1_num->SetBinError(15,0.3722682);
   h1_num->SetBinError(17,1.846391);
   h1_num->SetBinError(18,0.9396639);
   h1_num->SetBinError(19,9.550188);
   h1_num->SetBinError(20,6.683083);
   h1_num->SetBinError(21,18.50623);
   h1_num->SetMinimum(0);
   h1_num->SetMaximum(2);
   h1_num->SetEntries(5.577251);
   h1_num->SetLineStyle(0);
   h1_num->SetMarkerStyle(20);
   h1_num->SetMarkerSize(0.8);
   h1_num->GetXaxis()->SetTitle("#Delta#phi(MET,jets)");
   h1_num->GetXaxis()->SetLabelFont(42);
   h1_num->GetXaxis()->SetLabelSize(0.1);
   h1_num->GetXaxis()->SetTitleSize(0.19);
   h1_num->GetXaxis()->SetTitleOffset(0.85);
   h1_num->GetYaxis()->SetTitle("Data/Bkg");
   h1_num->GetYaxis()->SetNdivisions(505);
   h1_num->GetYaxis()->SetLabelFont(42);
   h1_num->GetYaxis()->SetLabelOffset(0.007);
   h1_num->GetYaxis()->SetLabelSize(0.1);
   h1_num->GetYaxis()->SetTitleSize(0.19);
   h1_num->GetYaxis()->SetTitleOffset(0.35);
   h1_num->GetZaxis()->SetLabelFont(42);
   h1_num->GetZaxis()->SetLabelOffset(0.007);
   h1_num->GetZaxis()->SetLabelSize(0.05);
   h1_num->GetZaxis()->SetTitleSize(0.06);
   h1_num->GetZaxis()->SetTitleFont(42);
   h1_num->Draw("E1");
   TLine *line = new TLine(2.3,1,3.141593,1);
   line->Draw();
   lower->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
