{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Thu Oct 29 15:31:41 2015) by ROOT version5.34/18
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(0,0,1,1);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.15);
   c1_n2->SetRightMargin(0.15);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.15);
   c1_n2->SetFrameFillStyle(0);
   c1_n2->SetFrameBorderMode(0);
   
   TH1D *SelDiParton_DEta = new TH1D("SelDiParton_DEta","SelDiParton_DEta",50,0,10);
   SelDiParton_DEta->SetBinContent(1,2);
   SelDiParton_DEta->SetBinContent(2,3);
   SelDiParton_DEta->SetBinContent(3,2);
   SelDiParton_DEta->SetBinContent(4,4);
   SelDiParton_DEta->SetBinContent(6,2);
   SelDiParton_DEta->SetBinContent(7,5);
   SelDiParton_DEta->SetBinContent(8,5);
   SelDiParton_DEta->SetBinContent(9,4);
   SelDiParton_DEta->SetBinContent(10,10);
   SelDiParton_DEta->SetBinContent(11,6);
   SelDiParton_DEta->SetBinContent(12,15);
   SelDiParton_DEta->SetBinContent(13,15);
   SelDiParton_DEta->SetBinContent(14,22);
   SelDiParton_DEta->SetBinContent(15,28);
   SelDiParton_DEta->SetBinContent(16,34);
   SelDiParton_DEta->SetBinContent(17,35);
   SelDiParton_DEta->SetBinContent(18,62);
   SelDiParton_DEta->SetBinContent(19,62);
   SelDiParton_DEta->SetBinContent(20,85);
   SelDiParton_DEta->SetBinContent(21,112);
   SelDiParton_DEta->SetBinContent(22,161);
   SelDiParton_DEta->SetBinContent(23,201);
   SelDiParton_DEta->SetBinContent(24,268);
   SelDiParton_DEta->SetBinContent(25,394);
   SelDiParton_DEta->SetBinContent(26,467);
   SelDiParton_DEta->SetBinContent(27,629);
   SelDiParton_DEta->SetBinContent(28,814);
   SelDiParton_DEta->SetBinContent(29,1023);
   SelDiParton_DEta->SetBinContent(30,1330);
   SelDiParton_DEta->SetBinContent(31,1652);
   SelDiParton_DEta->SetBinContent(32,1921);
   SelDiParton_DEta->SetBinContent(33,2030);
   SelDiParton_DEta->SetBinContent(34,1696);
   SelDiParton_DEta->SetBinContent(35,1289);
   SelDiParton_DEta->SetBinContent(36,972);
   SelDiParton_DEta->SetBinContent(37,734);
   SelDiParton_DEta->SetBinContent(38,539);
   SelDiParton_DEta->SetBinContent(39,404);
   SelDiParton_DEta->SetBinContent(40,297);
   SelDiParton_DEta->SetBinContent(41,177);
   SelDiParton_DEta->SetBinContent(42,141);
   SelDiParton_DEta->SetBinContent(43,92);
   SelDiParton_DEta->SetBinContent(44,52);
   SelDiParton_DEta->SetBinContent(45,39);
   SelDiParton_DEta->SetBinContent(46,20);
   SelDiParton_DEta->SetBinContent(47,12);
   SelDiParton_DEta->SetBinContent(48,3);
   SelDiParton_DEta->SetBinContent(49,1);
   SelDiParton_DEta->SetEntries(17871);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   SelDiParton_DEta->SetLineColor(ci);
   SelDiParton_DEta->GetXaxis()->SetTitle("Selected Diparton - #Delta#eta");
   SelDiParton_DEta->GetXaxis()->SetRange(1,100);
   SelDiParton_DEta->GetXaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetXaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetXaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetXaxis()->SetTitleFont(42);
   SelDiParton_DEta->GetYaxis()->SetTitle("Number of events");
   SelDiParton_DEta->GetYaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetYaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetYaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetYaxis()->SetTitleOffset(1.75);
   SelDiParton_DEta->GetYaxis()->SetTitleFont(42);
   SelDiParton_DEta->GetZaxis()->SetLabelFont(42);
   SelDiParton_DEta->GetZaxis()->SetLabelSize(0.035);
   SelDiParton_DEta->GetZaxis()->SetTitleSize(0.035);
   SelDiParton_DEta->GetZaxis()->SetTitleFont(42);
   SelDiParton_DEta->Draw("");
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
