{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Wed Nov 18 19:31:14 2015) by ROOT version5.34/18
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(0,0,1,1);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.15);
   c1_n2->SetRightMargin(0.15);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.15);
   c1_n2->SetFrameFillStyle(0);
   c1_n2->SetFrameBorderMode(0);
   
   TH1D *LeadDijet_DEta = new TH1D("LeadDijet_DEta","LeadDijet_DEta",50,0,10);
   LeadDijet_DEta->SetBinContent(16,53);
   LeadDijet_DEta->SetBinContent(17,78);
   LeadDijet_DEta->SetBinContent(18,102);
   LeadDijet_DEta->SetBinContent(19,121);
   LeadDijet_DEta->SetBinContent(20,181);
   LeadDijet_DEta->SetBinContent(21,225);
   LeadDijet_DEta->SetBinContent(22,241);
   LeadDijet_DEta->SetBinContent(23,325);
   LeadDijet_DEta->SetBinContent(24,398);
   LeadDijet_DEta->SetBinContent(25,456);
   LeadDijet_DEta->SetBinContent(26,624);
   LeadDijet_DEta->SetBinContent(27,796);
   LeadDijet_DEta->SetBinContent(28,974);
   LeadDijet_DEta->SetBinContent(29,1152);
   LeadDijet_DEta->SetBinContent(30,1444);
   LeadDijet_DEta->SetBinContent(31,1535);
   LeadDijet_DEta->SetBinContent(32,1587);
   LeadDijet_DEta->SetBinContent(33,1358);
   LeadDijet_DEta->SetBinContent(34,994);
   LeadDijet_DEta->SetBinContent(35,762);
   LeadDijet_DEta->SetBinContent(36,519);
   LeadDijet_DEta->SetBinContent(37,403);
   LeadDijet_DEta->SetBinContent(38,317);
   LeadDijet_DEta->SetBinContent(39,185);
   LeadDijet_DEta->SetBinContent(40,131);
   LeadDijet_DEta->SetBinContent(41,80);
   LeadDijet_DEta->SetBinContent(42,59);
   LeadDijet_DEta->SetBinContent(43,38);
   LeadDijet_DEta->SetBinContent(44,19);
   LeadDijet_DEta->SetBinContent(45,8);
   LeadDijet_DEta->SetBinContent(46,2);
   LeadDijet_DEta->SetBinContent(47,1);
   LeadDijet_DEta->SetBinContent(48,1);
   LeadDijet_DEta->SetEntries(15169);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   LeadDijet_DEta->SetLineColor(ci);
   LeadDijet_DEta->GetXaxis()->SetTitle("Lead Generator Dijet #Delta#eta");
   LeadDijet_DEta->GetXaxis()->SetRange(1,200);
   LeadDijet_DEta->GetXaxis()->SetLabelFont(42);
   LeadDijet_DEta->GetXaxis()->SetLabelSize(0.035);
   LeadDijet_DEta->GetXaxis()->SetTitleSize(0.035);
   LeadDijet_DEta->GetXaxis()->SetTitleFont(42);
   LeadDijet_DEta->GetYaxis()->SetTitle("Events");
   LeadDijet_DEta->GetYaxis()->SetLabelFont(42);
   LeadDijet_DEta->GetYaxis()->SetLabelSize(0.035);
   LeadDijet_DEta->GetYaxis()->SetTitleSize(0.035);
   LeadDijet_DEta->GetYaxis()->SetTitleOffset(1.75);
   LeadDijet_DEta->GetYaxis()->SetTitleFont(42);
   LeadDijet_DEta->GetZaxis()->SetLabelFont(42);
   LeadDijet_DEta->GetZaxis()->SetLabelSize(0.035);
   LeadDijet_DEta->GetZaxis()->SetTitleSize(0.035);
   LeadDijet_DEta->GetZaxis()->SetTitleFont(42);
   LeadDijet_DEta->Draw("");
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
